document.addEventListener('DOMContentLoaded', () => {
    const prompts = {
        en: [
          "Superman vs Batman: Which one would you want to be?",
          "Ability to breathe fire vs Ability to freeze things",
          "Ability to fly vs Ability to become invisible",
          "If you acquired a superpower, could you keep it a secret?",
          "Ability to change your appearance vs Ability to produce money",
          "What would you do if your friends found out about your superpower?",
          "What job do you think AI will take over next?",
          "Would you like to ride in an AI-powered car?",
          "A chore you wish AI could do for you.",
          "If you could create a world in Games just by speaking, what would you say?",
          "What do you think the future of AI will be like?",
          "If your online friend turned out to be an AI from the future, would you continue the friendship?",
          "Favorite anime song",
          "Favorite anime",
          "An anime character you can draw from memory",
          "Anime character you'd like to become",
          "The first anime you watched",
          "If you could freely create an anime, what kind of anime would it be?",
          "Favorite board game",
          "Do you own any board games?",
          "Board games you are good at or struggle with",
          "If you were to create a board game, what would it be like?",
          "Would you participate in a game where losing means losing all your possessions, but winning makes you rich?",
          "Memories related to board games",
          "Recommended book",
          "Which do you read more often? Manga vs Novels",
          "The book that influenced you the most",
          "A novel or manga you wish to be made into a movie or anime",
          "If you were to write a book, what kind of book would it be?",
          "Do you think physical books should become obsolete?",
          "What kind of car do you like?",
          "The most expensive car you've ever seen",
          "Are you good at driving?",
          "If you could create the world's strongest car, what would it be like?",
          "What do you look for in a car: Price, safety, or brand?",
          "What features do you think cars will have in 100 years?",
          "If you could become a cat, what would you want to do?",
          "If you were to get a cat, what breed would you choose?",
          "Understand cat language vs Control cats at will",
          "Favorite cat from a story",
          "How would you design your ideal cat cafe?",
          "What would you do if you found an excessively cute stray cat?",
          "Talk about a Christmas gift you received",
          "If you could become either Santa Claus or a reindeer, which would you choose?",
          "What do you eat for Christmas?",
          "Recommended Christmas movie",
          "How will you spend Christmas this year?",
          "Memories of Christmas",      "Favorite clothing brand",
          "Favorite fashion coordination",
          "Do you often wear hats?",
          "Plain vs flashy patterns",
          "Can you wear clothes given to you by an ex-partner?",
          "An item of clothing you can't throw away and its memory",
          "Do you ever perceive colors or smells when thinking about numbers or musical notes?",
          "If you could only choose five crayon colors, which would you pick?",
          "What color represents your current mood?",
          "Favorite color",
          "If all food turned either blue or red, which would you choose?",
          "What color clothes do you wear often?",
          "What environmentally friendly thing have you done recently?",
          "Do you consider the environment when shopping?",
          "Preference for trains over cars",
          "Do you pay attention to sorting garbage?",
          "Have you ever gone on a trash pickup?",
          "Do you think your town is clean?",
          "Have you ever tried a diet?",
          "Food you dislike",
          "Favorite sweets",
          "Something you eat too much of",
          "Recommended restaurant",
          "In delicious food, what's more important: Taste, location, or company?",
          "Favorite game",
          "Favorite game genre",
          "Do you have any game cartridges you can't throw away?",
          "PC vs Smartphone",
          "Pros of high-quality graphics in games vs Pros of 32-bit games",
          "In gaming, what's more important: Experience or story?",
          "When you think of Halloween, which character comes to mind?",
          "A character you'd like to cosplay for Halloween",
          "Your thoughts on the differences between Halloween culture in Japan and abroad",
          "Have you ever made a Jack-o'-lantern?",
          "Recommended ways to spend Halloween",
          "If you could get endless candy, how much would you want?",
          "Your hobby",
          "Something you're often warned about by friends or family",
          "Introduce yourself to someone you've just met",
          "Something you disliked as a child but can eat now",
          "Your favorite way to spend time",
          "A peculiar habit of yours that even you think is strange",
          "Favorite musical instrument",
          "Recommended music event in Games",
          "Favorite song",
          "Song you like to listen to on rainy days",
          "Song with special memories",
          "Recommended singer in Games",
          "Favorite way to spend New Year",
          "A unique New Year tradition in your family",
          "Memories of last year's New Year",
          "How your country celebrates New Year",
          "Something you always do when the New Year arrives",
          "What was your New Year's resolution last year?",
          "Favorite painting",
          "Have you seen any famous paintings?",
          "Preference: Digital or analog?",
          "Recommended art museum",
          "Favorite historical painter",
          "Have you ever bought an expensive painting?",
          "Do you have a high-end graphics card?",
          "Your first PC purchase",
          "Mac, Windows, or other?",
          "Appearance vs High functionality",
          "Do you have a multi-display setup?",
          "If you could receive one for free, which would you choose: high-end gaming mouse vs high-end gaming chair?",
          "Are you usually confessed to, or do you confess?",
          "Can a student-teacher relationship work?",
          "Who has the final say in choosing a partner: Rationality or intuition?",
          "Long-distance relationship vs Age-gap relationship",
          "Can language be a barrier in love?",
          "Your ideal partner",
          "A person you admire",
          "A historical figure you respect",
          "Favorite proverb",
          "The type of person you respect",
          "A recent action by someone that moved you",
          "The kind of person you aspire to be",
          "Do you prefer the sea or the mountains?",
          "Have you ever surfed?",
          "A mishap you had at the sea",
          "Are you good at swimming?",
          "Which ability is more appealing: World's best long-distance swimmer vs World's best free diver",
          "Memories of the sea",
          "The longest you've ever slept",
          "The strangest nightmare you've had",
          "The longest you've stayed awake",
          "If you could only bring a pillow or blanket to a deserted island, which would you choose?",
          "Have you ever slept in class?",
          "A story about oversleeping",
          "What was your post about that received over 10,000 likes suddenly?",
          "Have you ever had a post liked by a celebrity?",
          "Do you follow more people than you have followers?",
          "Instagram over Twitter",
          "An internet service you used in the past",
          "What do you think future social networks will be like?",
          "What is your favorite stuffed animal?",
          "If your stuffed animal could talk, what do you think it would say?",
          "If you could have a Games avatar as a stuffed animal, which would you choose?",
          "If you could add one stuffed animal to your room today, what would it be?",
          "If you could create a cute stuffed animal by mixing two animals, what would you mix?",
          "If making stuffed animals was your job, what would you make?",
          "If you could have plastic surgery on any part of your body, what would you change?",
          "Do you prefer double eyelids or single eyelids?",
          "Do you have a tattoo you want to remove?",
          "A part of your body that you feel self-conscious about that others might not understand",
          "If you could change your race or gender for a day like changing an avatar, what would you choose?",
          "A pill that makes you look 10 years younger vs A pill that makes you 10 years healthier",
          "Favorite candy",
          "If you could have unlimited access to one candy, what would it be?",
          "Candy you've made yourself",
          "Expensive $300 candy vs 300 pieces of $1 candy",
          "Candy you dislike",
          "In candy, what's more important: Appearance, taste, or price?",
          "Memories of an overseas trip",
          "If you could go to a cold country in summer, where would you like to go?",
          "If you could teleport to any country, which would you choose?",
          "Which do you find more challenging: boats or airplanes?",
          "A foreign dish you want to try",
          "A historic building in the world you want to see",
          "Recommended YouTuber",
          "A video that recently made you laugh",
          "Videos you end up watching unintentionally",
          "Recommended videos for language learning",
          "Your frequently watched video genre",
          "Video type you dislike",
          "Would you like to become an actor or voice actor?",
          "Favorite actor/voice actor",
          "If you got a role in a Hollywood movie, what character would you play?",
          "If you could be a famous actor/voice actor for a day, what would you do?",
          "If you could be a motion actor for a 3D character, what kind of character would you like to play?",
          "Show us an impression you're good at!",
          "Are you quick to take baths?",
          "Do you have a personal shampoo?",
          "Is there a hot spring you want to visit?",
          "If you had to leave either body soap or shampoo at home when traveling, which would you choose?",
          "Do you struggle with hot water?",
          "How long can you endure in a sauna?",
          "Have you ever gone camping?",
          "Have you slept in a tent?",
          "Memories of a BBQ",
          "Would you like to live in a treehouse?",
          "Would you like to try solo camping?",
          "What comes to mind when you think of camp food?",
          "A recent incident that made you cry",
          "Are you someone who cries easily?",
          "Have you ever cried because food was too spicy?",
          "Can you cry on command within a minute?",
          "A movie that makes you cry",
          "A story about something so painful it made you cry",
          "Something that recently disappointed you",
          "Something you find hopeless",
          "The worst way to die, in your opinion",
          "Something about the world that makes you despair",
          "Which is more despairing: Your phone battery dying when you're out or forgetting your phone?",
          "What's worse: Being forgotten by a close friend or running into someone you dislike?",
          "What would you sacrifice to become rich?",
          "Childhood dream",
          "Someone you'd like to meet",
          "A luxurious food you want to try",
          "Your ideal lifestyle",
          "A skill you want to acquire",
          "What is your best subject?",
          "A food you dislike?",
          "A skill you believe you're unbeatable at",
          "Do you prefer to finish things you're good at or bad at first?",
          "Do you have any books you bought but haven't finished reading?",
          "A place you find uncomfortable?",
          "What does happiness mean to you?",
          "If happiness levels ranged from 1 to 10, what food would be level 1?",
          "Quietness or noise, which brings you more happiness?",
          "A personal happiness you think might be unique to you",
          "The difference between wealth and happiness",
          "The happiest animal in the world, in your opinion",
          "What is a specialty of your hometown?",
          "Memories of your hometown",
          "Tourist attractions in your hometown",
          "Any famous people from your hometown?",
          "Do you still live in your hometown?",
          "Have you ever had a class reunion?",
          "The last lie you told",
          "Do you consider yourself a truthful person?",
          "A room with one liar vs a room where everyone lies",
          "Tell a believable lie",
          "A true story that sounds like a lie",
          "What level of lie can you tolerate?",
          "Have you been to a wedding?",
          "Your ideal married life",
          "Your ideal marriage partner",
          "Do you know of an ideal couple?",
          "Would you marry someone with children?",
          "How many children would you like to have if you got married?",
          "Your favorite way to spend the morning",
          "Your favorite breakfast",
          "Are you a night owl or an early bird?",
          "Music you like to listen to in the morning",
          "A daily morning routine",
          "Have you ever experienced sleep paralysis?",
          "The last movie you watched",
          "Movie recommendation",
          "Top 3 movies of the year",
          "A movie you watch every year",
          "Has a remake ever been better than the original?",
          "Favorite movie genre",
          "Something you can't tolerate",
          "Food you can't resist if it's in front of you",
          "Which can't you tolerate more: Being stood up or having something you lent sold?",
          "What would you do if you were proposed to in a flash mob?",
          "Can you tolerate hearing bad things about your family or friends?",
          "Something that angered you recently",
          "Do you have a pet?",
          "What pets have you had?",
          "How old is your pet?",
          "Should pet shops be abolished?",
          "If you could have any animal in the world as a pet, what would it be?",
          "A fictional animal you'd like as a pet",
          "Favorite plant",
          "Do you often pick up leaves, flowers, or seeds in the park?",
          "Do you have any plants you are growing?",
          "Have you grown and eaten your own fruits or vegetables?",
          "If you could create an original plant, what would it be?",
          "Favorite flower",
          "What games did you play a lot as a child?",
          "A game popular only in your area",
          "Games you played a lot at school",
          "A toy or game you wanted as a child but couldn't afford",
          "Recommended card game",
          "Are you good at hide and seek?",
          "Are you saving money?",
          "Do you consider yourself frugal or a spender?",
          "If you have a secret saving tip, please share",
          "What's more important: Money or experiences?",
          "Unlimited frozen food vs Unlimited fresh vegetables: Which is more luxurious?",
          "A month without electricity vs A month without water",
          "Do you smoke? If not, why?",
          "Do you know someone who successfully quit smoking?",
          "Do you think smoking is harmful to health?",
          "What are your thoughts on electronic cigarettes?",
          "How many cigarettes a day makes someone a heavy smoker?",
          "Have you ever smoked a cigar?",
          "Favorite sport",
          "Is there a sports team you can't help but support?",
          "Favorite athlete",
          "A sport you haven't tried yet",
          "A sport whose rules you don't fully understand",
          "Do you think eSports should be an Olympic sport?",
          "If you could invent a new holiday, what would it be?",
          "Your favorite childhood memory",
          "The most challenging puzzle or game you've ever faced",
          "A technology you wish existed",
          "The most interesting documentary you've ever watched",
          "If you could have dinner with any fictional character, who would it be?",
          "The best advice you've ever received",
          "A skill you'd like to learn in the next year",
          "Your favorite tradition or celebration",
          "The most beautiful place you've ever visited",
          "A book that changed your perspective on life",
          "The funniest joke you know",
          "A project or hobby you're currently working on",
          "Your ideal way to spend a lazy day",
          "A cause you are passionate about",
          "The last thing that made you laugh out loud",
          "A goal you've set for yourself this year",
          "Your favorite way to relax and unwind",
          "A random act of kindness you've experienced",
          "Your favorite season and why",
          "The last movie that made you cry",
          "A historical period you find fascinating",
          "Your favorite type of cuisine",
          "An invention you think has changed the world for the better",
          "Your favorite quote and its significance to you",
          "A fear you've overcome",
          "The best concert or live performance you've ever attended",
          "Your dream vacation destination",
          "A talent you possess that people might not expect",
          "The most memorable gift you've ever received",
          "A language you'd love to learn",
          "Your favorite type of weather",
          "An item on your bucket list",
          "The best meal you've ever had",
          "A book or movie that made you think differently",
          "An artist or band you love that most people haven't heard of",
          "Your favorite outdoor activity",
          "A puzzle or game that you can't solve but wish you could",
          "The most impactful lesson you learned from a mistake",
          "A habit you're trying to break or develop",
          "Your favorite way to celebrate an accomplishment",
          "A piece of technology you can't live without",
          "An unusual skill or party trick you can perform",
          "The most interesting place you've ever explored",
          "Your favorite childhood book",
          "A hobby you picked up during quarantine",
          "The most challenging thing about growing up",
          "Your favorite podcast and why",
          "An achievement you're proud of",
          "The best piece of life advice you've ever gotten",
          "A random fact you find interesting",
          "The most heartwarming thing you've witnessed",
          "Your favorite board or card game to play with friends",
          "A personal rule you never break",
          "The last good deed you did",
          "A movie that always makes you feel good",
          "Your favorite place to escape to when you need peace",
          "A subject you wish you knew more about",
          "The most unusual food you've ever tried",
          "Your favorite way to spend time with family",
        ],
        ja: [
          "スーパーマン対バットマン：どちらになりたいですか？",
          "火を吹く能力対物を凍らせる能力",
          "飛ぶ能力対透明になる能力",
          "もし超能力を手に入れたら、秘密にできますか？",
          "外見を変える能力対お金を生み出す能力",
          "友人があなたの超能力を知ったら、どうしますか？",
          "AIが次に取って代わると思う仕事は何ですか？",
          "AI駆動の車に乗りたいですか？",
          "AIにやってほしい家事は何ですか？",
          "もし話すだけでゲーム内に世界を作れるとしたら、何と言いますか？",
          "AIの未来はどうなると思いますか？",
          "オンラインの友人が未来から来たAIだったら、その友情を続けますか？",
          "好きなアニメソング",
          "好きなアニメ",
          "記憶から描けるアニメキャラクター",
          "なりたいアニメキャラクター",
          "最初に見たアニメ",
          "自由にアニメを作れるとしたら、どんなアニメにしますか？",
          "好きなボードゲーム",
          "ボードゲームを持っていますか？",
          "得意または苦手なボードゲーム",
          "もしボードゲームを作るなら、どんなものにしますか？",
          "負けたら全財産を失うが、勝てば豊かになれるゲームに参加しますか？",
          "ボードゲームにまつわる思い出",
          "おすすめの本",
          "よく読むのはマンガ対小説どちらですか？",
          "最も影響を受けた本",
          "映画やアニメにしてほしい小説またはマンガ",
          "もし本を書くなら、どんな本にしますか？",
          "紙の本は廃れるべきだと思いますか？",
          "好きな車の種類",
          "今まで見た中で最も高価な車",
          "運転は得意ですか？",
          "世界最強の車を作るとしたら、どんな車にしますか？",
          "車選びで重視するのは価格、安全性、それともブランド？",
          "100年後の車にはどんな機能があると思いますか？",
          "猫になれるとしたら、何をしたいですか？",
          "猫を飼うなら、どの品種を選びますか？",
          "猫の言葉を理解する能力対猫を自由に操る能力",
          "物語の中の好きな猫",
          "理想の猫カフェのデザインは？",
          "あまりにもかわいい野良猫を見つけたら、どうしますか？",
          "もらったクリスマスプレゼントについて話してください",
          "サンタクロースとトナカイのどちらになりたいですか？",
          "クリスマスに何を食べますか？",
          "おすすめのクリスマス映画",
          "今年のクリスマスはどう過ごしますか？",
          "クリスマスの思い出",
          // この下に残りのプロンプトを翻訳して追加してください...
          "好きな服のブランド",
          "好きなファッションコーディネート",
          "帽子はよくかぶりますか？",
          "シンプル対派手な柄",
          "元恋人からもらった服を着ますか？",
          "捨てられない服とその思い出",
          "数字や音符を考えるときに色や匂いを感じることがありますか？",
          "もしクレヨンを5色だけ選べるとしたら、どれを選びますか？",
          "現在の気分を表す色は何色ですか？",
          "好きな色",
          "もし全ての食べ物が青色か赤色になるとしたら、どちらを選びますか？",
          "よく着る服の色は何色ですか？",
          "最近した環境に優しいことは何ですか？",
          "買い物をするとき、環境を考慮しますか？",
          "車よりも電車を好む",
          "ゴミの分別に注意していますか？",
          "ゴミ拾いに行ったことがありますか？",
          "あなたの街はきれいだと思いますか？",
          "ダイエットを試みたことがありますか？",
          "苦手な食べ物は？",
          "好きなお菓子",
          "食べ過ぎてしまうもの",
          "おすすめのレストラン",
          "おいしい食べ物において、味、場所、同伴者のどれが重要ですか？",
          "好きなゲーム",
          "好きなゲームジャンル",
          "捨てられないゲームカートリッジがありますか？",
          "PC対スマートフォン",
          "高品質グラフィックのゲームの長所対32ビットゲームの長所",
          "ゲームにおいて、体験とストーリーのどちらが重要ですか？",
          "ハロウィンと聞いて思い浮かぶキャラクターは？",
          "ハロウィンのためにコスプレしたいキャラクター",
          "日本と海外のハロウィン文化の違いについてどう思いますか？",
          "ジャックオーランタンを作ったことがありますか？",
          "ハロウィンを過ごすおすすめの方法",
          "もし無限にキャンディをもらえるとしたら、どれくらい欲しいですか？",
          "あなたの趣味",
          "友人や家族からよく注意されること",
          "初めて会った人に自己紹介するときに何を言いますか？",
          "子供の頃は嫌いだったけど、今は食べられるもの",
          "好きな過ごし方",
          "自分でも変だと思う変わった習慣",
          "好きな楽器",
          "ゲームでおすすめの音楽イベント",
          "好きな曲",
          "雨の日に聞きたい曲",
          "特別な思い出のある曲",
          "ゲームでおすすめの歌手",
          "お正月の過ごし方",
          "家族独自のお正月の伝統",
          "去年のお正月の思い出",
          "あなたの国のお正月の祝い方",
          "お正月に必ずすること",
          "去年のお正月の抱負は何でしたか？",
          "好きな絵画",
          "有名な絵画を見たことがありますか？",
          "デジタル対アナログの好み",
          "おすすめの美術館",
          "好きな歴史上の画家",
          "高価な絵画を買ったことがありますか？",
          "高性能グラフィックカードを持っていますか？",
          "最初に購入したPC",
          "Mac、Windows、それともその他？",
          "外見対高機能性",
          "マルチディスプレイのセットアップを持っていますか？",
          "もし無料で一つもらえるとしたら、高性能ゲーミングマウスと高性能ゲーミングチェアのどちらを選びますか？",
          "普段は告白される方ですか、それとも告白する方ですか？",
          "教師と生徒の関係はうまくいくと思いますか？",
          "パートナー選びで最終的に決めるのは理性か直感か？",
          "遠距離恋愛対年の差恋愛",
          "言語は恋愛において障壁になり得ますか？",
          "理想のパートナー",
          "尊敬する人",
          "尊敬する歴史上の人物",
          "好きなことわざ",
          "尊敬するタイプの人",
          "最近、誰かの行動に感動しましたか？",
          "目指したい人物像",
          "海と山、どちらが好きですか？",
          "サーフィンをしたことがありますか？",
          "海でのハプニング",
          "泳ぎは得意ですか？",
          "どちらの能力が魅力的ですか？世界最高の長距離泳者対世界最高のフリーダイバー",
          "海に関する思い出",
          "一番長く寝たことがある時間は？",
          "最も奇妙な悪夢",
          "最も長く起きていた時間",
          "無人島に持って行けるのが枕か毛布のどちらかだったら、どちらを選びますか？",
          "授業中に寝たことがありますか？",
          "寝坊した話",
          "いきなり1万いいねをもらった投稿は何でしたか？",
          "有名人にいいねされたことがありますか？",
          "フォローしている人数よりフォロワーが多いですか？",
          "Instagram対Twitter",
          "過去に使っていたインターネットサービス",
          "将来のソーシャルネットワークはどうなると思いますか？",
          "好きなぬいぐるみ",
          "もしぬいぐるみが話せるとしたら、何と言うと思いますか？",
          "ゲームのアバターをぬいぐるみにできるとしたら、どれを選びますか？",
          "今日、部屋に一つぬいぐるみを加えるとしたら、何にしますか？",
          "二つの動物を混ぜてかわいいぬいぐるみを作るとしたら、何と何を混ぜますか？",
          "ぬいぐるみを作るのが仕事だったら、何を作りますか？",
          "体のどの部分を整形したいですか？",
          "二重まぶたと一重まぶた、どちらが好みですか？",
          "消したいタトゥーはありますか？",
          "他人には理解しづらいけど、自分がコンプレックスに感じる体の部分",
          "アバターを変えるように一日だけ人種や性別を変えられるとしたら、何を選びますか？",
          "10歳若返る薬と10歳健康になる薬、どちらを選びますか？",
          "好きなキャンディ",
          "一つだけ無限に手に入るキャンディがあるとしたら、何を選びますか？",
          "自分で作ったキャンディ",
          "300ドルの高価なキャンディと1ドルのキャンディ300個、どちらを選びますか？",
          "苦手なキャンディ",
          "キャンディにおいて、見た目、味、価格のどれが重要ですか？",
          "海外旅行の思い出",
          "夏に寒い国へ行くとしたら、どこに行きたいですか？",
          "テレポートでどの国にも行けるとしたら、どこに行きますか？",
          "船と飛行機、どちらが乗りこなすのが難しいと思いますか？",
          "試してみたい外国の料理",
          "世界の歴史的建造物で見たいもの",
          "おすすめのYouTuber",
          "最近笑った動画",
          "意図せず見てしまう動画",
          "言語学習におすすめの動画",
          "よく見る動画のジャンル",
          "苦手な動画のタイプ",
          "俳優または声優になりたいですか？",
          "好きな俳優/声優",
          "ハリウッド映画に出演するなら、どんな役を演じたいですか？",
          "有名な俳優/声優に一日だけなれるとしたら、何をしますか？",
          "3Dキャラクターのモーションアクターになれるとしたら、どんなキャラクターを演じたいですか？",
          "得意な物まねを見せてください！",
          "お風呂は早めに入りますか？",
          "個人的なシャンプーはありますか？",
          "行ってみたい温泉はありますか？",
          "旅行に行くとき、ボディソープとシャンプーのどちらかを家に置いていくとしたら、どちらを選びますか？",
          "お湯が苦手ですか？",
          "サウナでどれくらい耐えられますか？",
          "キャンプに行ったことがありますか？",
          "テントで寝たことがありますか？",
          "BBQの思い出",
          "ツリーハウスに住んでみたいですか？",
          "ソロキャンプを試してみたいですか？",
          "キャンプ食で思い浮かぶもの",
          "最近泣いた出来事",
          "泣きやすいですか？",
          "辛いものを食べて泣いたことがありますか？",
          "1分以内に泣くことができますか？",
          "泣ける映画",
          "痛みで泣いた話",
          "最近失望したこと",
          "絶望的に感じること",
          "あなたにとって最悪の死に方",
          "世界のどこかで絶望を感じさせること",
          "電話のバッテリーが外出中に切れるのと、電話を忘れるのとでは、どちらが絶望的ですか？",
          "親しい友人に忘れられることと、嫌いな人に遭遇すること、どちらが悪いですか？",
          "豊かになるために何を犠牲にしますか？",
          "子供の頃の夢",
          "会いたい人",
          "試してみたい高級な食べ物",
          "理想のライフスタイル",
          "身につけたいスキル",
          "得意な科目は？",
          "苦手な食べ物は？",
          "自分が無敵だと思うスキル",
          "得意なことと苦手なこと、どちらを先に片付けますか？",
          "買ったけどまだ読んでいない本がありますか？",
          "居心地が悪い場所は？",
          "幸福についてどう思いますか？",
          "幸福度が1から10の範囲で、1の食べ物は何ですか？",
          "静けさと騒音、どちらが幸福をもたらしますか？",
          "自分にとってユニークな幸福は何ですか？",
          "富と幸福の違い",
          "世界で最も幸せな動物は何だと思いますか？",
          "故郷の名物は何ですか？",
          "故郷の思い出",
          "故郷の観光名所",
          "故郷の有名人は？",
          "まだ故郷に住んでいますか？",
          "同窓会に行ったことがありますか？",
          "最後についた嘘",
          "自分を正直な人だと思いますか？",
          "嘘つきが一人いる部屋と全員が嘘つきの部屋、どちらがいいですか？",
          "信じられる嘘を教えてください",
          "嘘のように聞こえる本当の話",
          "どのレベルの嘘を許容できますか？",
          "結婚式に行ったことがありますか？",
          "理想の結婚生活",
          "理想の結婚相手",
          "理想的なカップルを知っていますか？",
          "子供がいる人と結婚しますか？",
          "結婚したら何人の子供がほしいですか？",
          "朝の過ごし方",
          "好きな朝食",
          "夜型人間ですか、朝型人間ですか？",
          "朝に聞きたい音楽",
          "毎朝のルーチン",
          "金縛りを経験したことがありますか？",
          "最後に見た映画",
          "映画のおすすめ",
          "今年のトップ3映画",
          "毎年見る映画",
          "リメイクが原作より良かったことがありますか？",
          "好きな映画ジャンル",
          "我慢できないこと",
          "目の前にあったら抵抗できない食べ物",
          "待ち合わせで立ち上げられることと、貸したものを売られること、どちらが我慢できない？",
          "フラッシュモブでプロポーズされたらどうしますか？",
          "家族や友人の悪口を聞くのを我慢できますか？",
          "最近腹を立てたこと",
          "ペットはいますか？",
          "飼ったことのあるペット",
          "ペットの年齢は？",
          "ペットショップは廃止されるべきだと思いますか？",
          "もし世界中のどんな動物でもペットにできるとしたら、何を選びますか？",
          "ペットにしたい架空の動物",
          "好きな植物",
          "公園で葉っぱ、花、種をよく拾いますか？",
          "育てている植物はありますか？",
          "自分で育てて食べた果物や野菜がありますか？",
          "オリジナルの植物を作るとしたら、どんなものにしますか？",
          "好きな花",
          "子供の頃よく遊んだゲーム",
          "地域に特有の人気ゲーム",
          "学校でよく遊んだゲーム",
          "子供の頃欲しかったけど手に入らなかったおもちゃやゲーム",
          "おすすめのカードゲーム",
          "かくれんぼが得意ですか？",
          "お金を貯めていますか？",
          "節約派ですか、浪費派ですか？",
          "秘密の節約ティップがあれば教えてください",
          "お金と経験、どちらが重要ですか？",
          "無制限の冷凍食品対無制限の新鮮な野菜、どちらがより贅沢ですか？",
          "1ヶ月電気がない生活と1ヶ月水がない生活、どちらが厳しいですか？",
          "タバコを吸いますか？吸わないなら、なぜですか？",
          "成功して禁煙した人を知っていますか？",
          "タバコは健康に悪いと思いますか？",
          "電子タバコについてどう思いますか？",
          "1日に何本吸うとヘビースモーカーだと思いますか？",
          "葉巻を吸ったことがありますか？",
          "好きなスポーツ",
          "応援せずにはいられないスポーツチームはありますか？",
          "好きなアスリート",
          "まだ試したことのないスポーツ",
          "ルールを完全に理解していないスポーツ",
          "eスポーツはオリンピック競技になるべきだと思いますか？",
          "新しい祝日を作るとしたら、どんな日にしますか？",
          "子供の頃のお気に入りの思い出",
          "これまで直面した最も難しいパズルやゲーム",
          "存在してほしいと思う技術",
          "今まで見た中で最も興味深いドキュメンタリー",
          "架空のキャラクターと夕食を共にできるとしたら、誰を選びますか？",
          "今までで一番良いアドバイス",
          "来年中に学びたいスキル",
          "好きな伝統や祝日",
          "訪れた中で最も美しい場所",
          "人生観を変えた本",
          "知っている一番面白いジョーク",
          "現在取り組んでいるプロジェクトや趣味",
          "怠ける日を過ごす理想的な方法",
          "情熱を注いでいる原因",
          "大声で笑った最後のこと",
          "今年自分に課した目標",
          "リラックスしてリフレッシュする好きな方法",
          "経験したランダムな親切",
          "好きな季節とその理由",
          "最後に泣かせた映画",
          "魅力的だと思う歴史上の時期",
          "好きな料理の種類",
          "世界をより良い場所に変えたと思う発明",
          "好きな引用とそのあなたにとっての意味",
          "克服した恐怖",
          "参加した中で最高のコンサートやライブパフォーマンス",
          "夢の休暇先",
          "人があまり知らないかもしれないけど持っている才能",
          "今までで最も記憶に残る贈り物",
          "学びたい言語",
          "好きな天気",
          "バケットリストにある項目",
          "今までで最高の食事",
          "考え方を変えた本や映画",
          "ほとんどの人が知らないかもしれないけど好きなアーティストやバンド",
          "好きなアウトドアアクティビティ",
          "解けないけど解きたいパズルやゲーム",
          "間違いから学んだ最も影響力のある教訓",
          "やめたい、または身につけたい習慣",
          "成果を祝う好きな方法",
          "なくてはならない技術製品",
          "披露できる珍しいスキルやパーティートリック",
          "これまで探検した中で最も興味深い場所",
          "子供の頃好きだった本",
          "検疫中に始めた趣味",
          "成長する上で直面した最も大きな挑戦",
          "好きなポッドキャストとその理由",
          "誇りに思っている成果",
          "今までで最高の人生のアドバイス",
          "興味深いと思うランダムな事実",
          "目撃した最も心温まる出来事",
          "友達と遊ぶのに好きなボードゲームやカードゲーム",
          "絶対に破らない個人的なルール",
          "最後にした良い行い",
          "いつも気分を良くしてくれる映画",
          "平和を求めるときに逃げ込む好きな場所",
          "もっと知りたいと思う主題",
          "今まで試した中で最も珍しい食べ物",
          "家族と過ごす好きな方法",
        ],
        Ar: [
          "سوبرمان ضد باتمان: أيهما تفضل أن تكون؟","القدرة على التنفس بالنار مقابل القدرة على تجميد الأشياء",
          "القدرة على الطيران مقابل القدرة على الاختفاء",
          "إذا اكتسبت قوة خارقة، هل يمكنك الاحتفاظ بها سرًا؟",
          "القدرة على تغيير مظهرك مقابل القدرة على إنتاج المال",
          "ماذا ستفعل إذا اكتشف أصدقاؤك عن قوتك الخارقة؟",
          "ما هو العمل الذي تعتقد أن الذكاء الاصطناعي سيتولى مهامه التالية؟",
          "هل تود ركوب سيارة تعمل بالذكاء الاصطناعي؟",
          "مهمة تتمنى لو يمكن للذكاء الاصطناعي أن يقوم بها من أجلك.",
          "إذا كنت تستطيع إنشاء عالم في الألعاب بمجرد الكلام، ماذا ستقول؟",
          "كيف تعتقد أن مستقبل الذكاء الاصطناعي سيكون؟",
          "إذا اتضح أن صديقك عبر الإنترنت هو ذكاء اصطناعي من المستقبل، هل ستستمر في الصداقة؟",
          "أغنية أنمي مفضلة",
          "أنمي مفضل",
          "شخصية أنمي يمكنك رسمها من الذاكرة",
          "شخصية أنمي تود أن تصبح مثلها",
          "أول أنمي شاهدته",
          "إذا كان بإمكانك إنشاء أنمي بحرية، كيف سيكون ذلك الأنمي؟",
          "لعبة لوحية مفضلة",
          "هل تملك أي ألعاب لوحية؟",
          "ألعاب لوحية تجيد اللعب بها أو تجدها صعبة",
          "إذا كنت ستنشئ لعبة لوحية، كيف ستكون؟",
          "هل ستشارك في لعبة تعني الخسارة فيها خسارة كل ممتلكاتك، لكن الفوز يجعلك غنيًا؟",
          "ذكريات متعلقة بالألعاب اللوحية",
          "كتاب موصى به",
          "ماذا تقرأ أكثر؟ مانغا مقابل روايات",
          "الكتاب الذي أثر فيك أكثر شيء",
          "رواية أو مانغا تتمنى أن يتم تحويلها إلى فيلم أو أنمي",
          "إذا كنت ستكتب كتابًا، ما نوع الكتاب الذي سيكون؟",
          "هل تعتقد أن الكتب الورقية يجب أن تصبح قديمة؟",
          "ما نوع السيارة التي تحبها؟",
          "أغلى سيارة رأيتها على الإطلاق",
          "هل أنت جيد في القيادة؟",
          "إذا كنت تستطيع إنشاء أقوى سيارة في العالم، كيف ستكون؟",
          "ما الذي تبحث عنه في سيارة: السعر، الأمان، أم العلامة التجارية؟",
          "ما هي الميزات التي تعتقد أن السيارات ستمتلكها في غضون 100 عام؟",
          "إذا كنت تستطيع أن تصبح قطًا، ماذا كنت ترغب في القيام به؟",
          "إذا كنت ستحصل على قط، أي سلالة كنت ستختار؟",
          "فهم لغة القطط مقابل التحكم في القطط كما تشاء",
          "قطتك المفضلة من قصة",
          "كيف ستصمم مقهى القطط المثالي لك؟",
          "ماذا ستفعل إذا وجدت قطة ضالة شديدة اللطافة؟",
          "تحدث عن هدية عيد الميلاد التي تلقيتها",
          "إذا كنت تستطيع أن تصبح إما سانتا كلوز أو أحد الرنة، أيهما كنت ستختار؟",
          "ماذا تأكل في عيد الميلاد؟",
          "فيلم عيد الميلاد الموصى به",
          "كيف ستقضي عيد الميلاد هذا العام؟",
          "ذكريات عيد الميلاد",
          "العلامة التجارية المفضلة للملابس",
          "تنسيق الأزياء المفضل",
          "هل ترتدي القبعات كثيرًا؟",
          "الأنماط البسيطة مقابل الأنماط الفاقعة",
          "هل يمكنك ارتداء الملابس التي أعطاها لك شريك سابق؟",
          "قطعة ملابس لا يمكنك التخلص منها وذكرياتها",
          "هل تشعر أحيانًا بالألوان أو الروائح عند التفكير في الأرقام أو النوتات الموسيقية؟",
          "إذا كان بإمكانك اختيار خمسة ألوان من الأقلام الشمعية فقط، أيها ستختار؟",
          "ما هو اللون الذي يمثل مزاجك الحالي؟",
          "اللون المفضل",
          "إذا تحول كل الطعام إما إلى اللون الأزرق أو الأحمر، أيهما كنت ستختار؟",
          "ما هي الألوان التي ترتديها كثيرًا؟",
          "ما هي الأشياء الصديقة للبيئة التي قمت بها مؤخرًا؟",
          "هل تفكر في البيئة عند التسوق؟",
          "التفضيل للقطارات على السيارات",
          "هل تنتبه إلى فرز القمامة؟",
          "هل سبق لك أن شاركت في جمع القمامة؟",
          "هل تعتقد أن بلدتك نظيفة؟",
          "هل سبق لك أن جربت حمية؟",
          "الطعام الذي لا تحبه",
          "الحلويات المفضلة",
          "شيء تأكله كثيرًا",
          "مطعم موصى به",
          "في الطعام اللذيذ، ما هو الأهم: الطعم، الموقع، أم الشركة؟",
          "لعبة مفضلة",
          "نوع اللعبة المفضل",
          "هل لديك أي خراطيش ألعاب لا يمكنك التخلص منها؟",
          "الكمبيوتر الشخصي مقابل الهاتف الذكي",
          "مزايا الرسومات عالية الجودة في الألعاب مقابل مزايا ألعاب 32 بت",
          "في الألعاب، ما هو الأهم: التجربة أم القصة؟",
          "عندما تفكر في عيد الهالوين، أي شخصية تتبادر إلى الذهن؟",
          "شخصية تود التنكر على شكلها لعيد الهالوين",
          "آرائك حول الاختلافات بين ثقافة عيد الهالوين في اليابان والخارج",
          "هل سبق لك أن صنعت فانوس جاك؟",
          "طرق موصى بها لقضاء عيد الهالوين",
          "إذا كان بإمكانك الحصول على حلوى لا نهائية، كم كنت ترغب في الحصول؟",
          "هوايتك",
          "شيء يحذرك منه الأصدقاء أو العائلة كثيرًا",
          "قدم نفسك لشخص قابلته للتو",
          "شيء كنت تكرهه عندما كنت طفلًا ولكن يمكنك تناوله الآن",
          "طريقتك المفضلة لقضاء الوقت",
          "عادة غريبة لديك حتى أنت تجدها غريبة",
          "آلة موسيقية مفضلة",
          "حدث موسيقي موصى به في الألعاب",
          "أغنية مفضلة",
          "أغنية تحب الاستماع إليها في الأيام الممطرة",
          "أغنية ذات ذكريات خاصة",
          "مغني موصى به في الألعاب",
          "طريقتك المفضلة لقضاء السنة الجديدة",
          "تقليد فريد للسنة الجديدة في عائلتك",
          "ذكريات السنة الجديدة العام الماضي",
          "كيف يحتفل بلدك بالسنة الجديدة",
          "شيء دائمًا ما تفعله عندما تأتي السنة الجديدة",
          "ما كانت عزمك للسنة الجديدة في العام الماضي؟",
          "لوحة مفضلة",
          "هل رأيت أي لوحات شهيرة؟",
          "التفضيل: رقمي أم تناظري؟",
          "متحف فني موصى به",
          "رسام تاريخي مفضل",
          "هل سبق لك أن اشتريت لوحة باهظة الثمن؟",
          "هل لديك بطاقة رسومات عالية الجودة؟",
          "أول شراء لكمبيوتر شخصي",
          "ماك، ويندوز، أم غيرها؟",
          "المظهر مقابل الوظائف العالية",
          "هل لديك إعداد متعدد الشاشات؟",
          "إذا كان بإمكانك الحصول على واحد مجانًا، أيهما كنت ستختار: فأرة ألعاب عالية الجودة مقابل كرسي ألعاب عالي الجودة؟",
          "هل عادة ما يعترفون لك، أم أنك تعترف؟",
          "هل يمكن أن تنجح علاقة بين طالب ومعلم؟",
          "من له الكلمة الأخيرة في اختيار شريك: العقلانية أم الحدس؟",
          "علاقة عن بعد مقابل علاقة بفارق عمري",
          "هل يمكن أن تكون اللغة عائقًا في الحب؟",
          "شريكك المثالي",
          "شخص تحترمه",
          "شخصية تاريخية تحترمها",
          "مثل مفضل",
          "نوع الشخص الذي تحترمه",
          "فعل حديث من شخص أثر فيك",
          "النوع من الشخص الذي تطمح لأن تكون مثله",
          "هل تفضل البحر أم الجبال؟",
          "هل سبق لك أن ركبت الأمواج؟",
          "حادثة مؤسفة حدثت لك في البحر",
          "هل أنت جيد في السباحة؟",
          "أي قدرة أكثر جاذبية: أفضل سباح لمسافات طويلة في العالم مقابل أفضل غواص حر في العالم",
          "ذكريات البحر",
          "أطول فترة نمت فيها",
          "أغرب كابوس لديك",
          "أطول فترة بقيت مستيقظًا فيها",
          "إذا كان بإمكانك إحضار وسادة أو بطانية فقط إلى جزيرة مهجورة، أيهما كنت ستختار؟",
          "هل سبق لك أن نمت في الصف؟",
          "قصة عن النوم الزائد",
          "ما كان منشورك الذي حصل فجأة على أكثر من 10,000 إعجاب؟",
          "هل سبق لك أن حصلت على إعجاب من مشهور؟",
          "هل تتابع أشخاصًا أكثر مما لديك من متابعين؟",
          "إنستغرام مقابل تويتر",
          "خدمة إنترنت استخدمتها في الماضي",
          "كيف تعتقد أن شبكات التواصل الاجتماعي في المستقبل ستكون؟",
          "ما هو حيوانك المحشو المفضل؟",
          "إذا كان بإمكان حيوانك المحشو التحدث، ماذا تعتقد أنه سيقول؟",
          "إذا كان بإمكانك امتلاك أفاتار من الألعاب كحيوان محشو، أيهما كنت ستختار؟",
          "إذا كان بإمكانك إضافة حيوان محشو إلى غرفتك اليوم، ماذا سيكون؟",
          "إذا كان بإمكانك إنشاء حيوان محشو لطيف عن طريق خلط حيوانين، ماذا ستخلط؟",
          "إذا كان صنع الحيوانات المحشوة هو عملك، ماذا كنت ستصنع؟",
          "إذا كان بإمكانك إجراء عملية تجميل على أي جزء من جسمك، ماذا كنت ستغير؟",
          "هل تفضل الجفون المزدوجة أم الجفون الفردية؟",
          "هل لديك وشم ترغب في إزالته؟",
          "جزء من جسمك تشعر بالحرج منه وقد لا يفهمه الآخرون",
          "إذا كان بإمكانك تغيير عرقك أو جنسك ليوم واحد مثل تغيير الأفاتار، ماذا كنت ستختار؟",
          "حبة تجعلك تبدو أصغر بعشر سنوات مقابل حبة تجعلك أكثر صحة بعشر سنوات",
          "حلوى مفضلة",
          "إذا كان بإمكانك الحصول على وصول غير محدود إلى حلوى واحدة، ماذا ستكون؟",
          "حلوى صنعتها بنفسك",
          "حلوى باهظة الثمن بقيمة 300 دولار مقابل 300 قطعة من الحلوى بدولار واحد",
          "حلوى لا تحبها",
          "في الحلوى، ما هو الأهم: المظهر، الطعم، أو السعر؟",
          "ذكريات رحلة خارجية",
          "إذا كان بإمكانك الذهاب إلى بلد بارد في الصيف، أين كنت ترغب في الذهاب؟",
          "إذا كان بإمكانك التنقل الفوري إلى أي دولة، أيها كنت ستختار؟",
          "أيهما تجده أكثر تحديًا: القوارب أم الطائرات؟",
          "طبق أجنبي ترغب في تجربته",
          "مبنى تاريخي في العالم ترغب في رؤيته",
          "يوتيوبر موصى به",
          "فيديو جعلك تضحك مؤخرًا",
          "فيديوهات تجد نفسك تشاهدها دون قصد",
          "فيديوهات موصى بها لتعلم اللغة",
          "نوع الفيديو الذي تشاهده كثيرًا",
          "نوع الفيديو الذي لا تحبه",
          "هل تود أن تصبح ممثلًا أو مؤدي صوت؟",
          "ممثل/مؤدي صوت مفضل",
          "إذا حصلت على دور في فيلم هوليوودي، أي شخصية كنت ستلعب؟",
          "إذا كان بإمكانك أن تكون ممثلًا/مؤدي صوت مشهورًا ليوم واحد، ماذا كنت ستفعل؟",
          "إذا كان بإمكانك أن تكون ممثل حركة لشخصية ثلاثية الأبعاد، أي نوع من الشخصيات كنت تود أن تلعب؟",
          "أرنا انطباعًا جيدًا عندك!",
          "هل أنت سريع في الاستحمام؟",
          "هل لديك شامبو شخصي؟",
          "هل هناك ينابيع ساخنة ترغب في زيارتها؟",
          "إذا اضطررت لترك إما الصابون أو الشامبو في المنزل عند السفر، أيهما كنت ستختار؟",
          "هل تواجه صعوبة مع الماء الساخن؟",
          "كم من الوقت يمكنك الصمود في الساونا؟",
          "هل سبق لك أن ذهبت للتخييم؟",
          "هل نمت في خيمة؟",
          "ذكريات شواء",
          "هل تود العيش في بيت شجرة؟",
          "هل تود تجربة التخييم بمفردك؟",
          "ما يتبادر إلى ذهنك عندما تفكر في طعام المخيم؟",
          "حادثة حديثة جعلتك تبكي",
          "هل أنت شخص يبكي بسهولة؟",
          "هل سبق لك أن بكيت لأن الطعام كان حارًا جدًا؟",
          "هل يمكنك البكاء عند الطلب خلال دقيقة؟",
          "فيلم يجعلك تبكي",
          "قصة عن شيء مؤلم جدًا جعلك تبكي",
          "شيء خيب ظنك مؤخرًا",
          "شيء تجده يائسًا",
          "أسوأ طريقة للموت، في رأيك",
          "شيء عن العالم يجعلك تيأس",
          "أيهما أكثر يأسًا: نفاد بطارية هاتفك عندما تكون بالخارج أم نسيان هاتفك؟",
          "ما هو الأسوأ: أن ينساك صديق مقرب أم أن تصادف شخصًا لا تحبه؟",
          "ماذا كنت ستضحي لتصبح غنيًا؟",
          "حلم الطفولة",
          "شخص تود لقاءه",
          "طعام فاخر ترغب في تجربته",
          "أسلوب حياتك المثالي",
          "مهارة ترغب في اكتسابها",
          "ما هو أفضل مادة دراسية لديك؟",
          "طعام لا تحبه؟",
          "مهارة تعتقد أنك لا تقهر فيها",
          "هل تفضل إنهاء الأشياء التي أنت جيد فيها أم السيئة أولًا؟",
          "هل لديك كتب اشتريتها ولم تنهي قراءتها؟",
          "مكان تجده غير مريح؟",
          "ماذا يعني لك السعادة؟",
          "إذا كانت مستويات السعادة تتراوح من 1 إلى 10، ما هو الطعام الذي سيكون المستوى 1؟",
          "الهدوء أم الضوضاء، أيهما يجلب لك السعادة أكثر؟",
          "سعادة شخصية تعتقد أنها قد تكون فريدة لك",
          "الفرق بين الثراء والسعادة",
          "أسعد حيوان في العالم، في رأيك",
          "ما هو تخصص مسقط رأسك؟",
          "ذكريات مسقط رأسك",
          "معالم سياحية في مسقط رأسك",
          "هل هناك أشخاص مشهورون من مسقط رأسك؟",
          "هل لا تزال تعيش في مسقط رأسك؟",
          "هل سبق لك أن حضرت لقاءً للخريجين؟",
          "آخر كذبة قلتها",
          "هل تعتبر نفسك شخصًا صادقًا؟",
          "غرفة بها كاذب واحد مقابل غرفة يكذب فيها الجميع",
          "قل كذبة معقولة",
          "قصة حقيقية تبدو كالكذبة",
          "ما مستوى الكذبة التي يمكنك تحملها؟",
          "هل حضرت زفافًا؟",
          "حياتك الزوجية المثالية",
          "شريك الزواج المثالي",
          "هل تعرف زوجين مثاليين؟",
          "هل كنت تتزوج شخصًا لديه أطفال؟",
          "كم عدد الأطفال الذين ترغب في الحصول عليهم إذا تزوجت؟",
          "طريقتك المفضلة لقضاء الصباح",
          "إفطارك المفضل",
          "هل أنت شخص يستيقظ مبكرًا أم يسهر لوقت متأخر؟",
          "الموسيقى التي تحب الاستماع إليها في الصباح",
          "روتينك الصباحي اليومي",
          "هل سبق لك أن تعرضت لشلل النوم؟",
          "آخر فيلم شاهدته",
          "توصية فيلم",
          "أفضل 3 أفلام لهذا العام",
          "فيلم تشاهده كل عام",
          "هل كان هناك أي فيلم تجاوز الأصل؟",
          "نوع الفيلم المفضل",
          "شيء لا يمكنك تحمله",
          "طعام لا يمكنك مقاومته إذا كان أمامك",
          "أيهما لا يمكنك تحمله أكثر: أن يتم تجاهلك أو أن يتم بيع شيء أقرضته؟",
          "ماذا كنت ستفعل لو تم اقتراح الزواج منك في فلاش موب؟",
          "هل يمكنك تحمل سماع أشياء سيئة عن عائلتك أو أصدقائك؟",
          "شيء أغضبك مؤخرًا",
          "هل لديك حيوان أليف؟",
          "ما هي الحيوانات الأليفة التي كانت لديك؟",
          "كم عمر حيوانك الأليف؟",
          "هل يجب إلغاء محلات بيع الحيوانات الأليفة؟",
          "إذا كان بإمكانك امتلاك أي حيوان في العالم كحيوان أليف، ماذا سيكون؟",
          "حيوان خيالي تود امتلاكه كحيوان أليف",
          "نبات مفضل",
          "هل تلتقط الأوراق أو الزهور أو البذور في الحديقة كثيرًا؟",
          "هل لديك أي نباتات تقوم بزراعتها؟",
          "هل قمت بزراعة وأكل الفواكه أو الخضروات الخاصة بك؟",
          "إذا كان بإمكانك إنشاء نبات أصلي، كيف سيكون؟",
          "زهرة مفضلة",
          "ما هي الألعاب التي لعبتها كثيرًا عندما كنت طفلًا؟",
          "لعبة شعبية فقط في منطقتك",
          "ألعاب لعبتها كثيرًا في المدرسة",
          "لعبة أو لعبة كنت تريدها عندما كنت طفلًا لكن لم تتمكن من تحمل تكلفتها",
          "لعبة الورق الموصى بها",
          "هل أنت جيد في الاختباء والبحث؟",
          "هل تدخر المال؟",
          "هل تعتبر نفسك مقتصدًا أو مبذرًا؟",
          "إذا كان لديك نصيحة سرية للتوفير، من فضلك شاركها",
          "ما هو الأهم: المال أم التجارب؟",
          "الأطعمة المجمدة غير المحدودة مقابل الخضروات الطازجة غير المحدودة: أيهما أكثر فخامة؟",
          "شهر بدون كهرباء مقابل شهر بدون ماء",
          "هل تدخن؟ إذا لا، لماذا؟",
          "هل تعرف شخصًا نجح في الإقلاع عن التدخين؟",
          "هل تعتقد أن التدخين ضار بالصحة؟",
          "ما رأيك في السجائر الإلكترونية؟",
          "كم عدد السجائر في اليوم يجعل شخصًا مدخنًا كثيرًا؟",
          "هل سبق لك أن دخنت سيجارة؟",
          "رياضة مفضلة",
          "هل هناك فريق رياضي لا يمكنك إلا أن تدعمه؟",
          "رياضي مفضل",
          "رياضة لم تجربها بعد",
          "رياضة قواعدها لا تفهمها بالكامل",
          "هل تعتقد أن الرياضات الإلكترونية يجب أن تكون رياضة أولمبية؟",
          "إذا كان بإمكانك اختراع عطلة جديدة، ماذا ستكون؟",
          "ذكرى طفولتك المفضلة",
          "أصعب لغز أو لعبة واجهتها على الإطلاق",
          "تقنية تتمنى لو كانت موجودة",
          "أكثر وثائقي مثير للاهتمام شاهدته على الإطلاق",
          "إذا كان بإمكانك تناول العشاء مع أي شخصية خيالية، من سيكون؟",
          "أفضل نصيحة تلقيتها على الإطلاق",
          "مهارة تود تعلمها في العام المقبل",
          "تقليدك أو احتفالك المفضل",
          "أجمل مكان زرته على الإطلاق",
          "كتاب غيّر وجهة نظرك حول الحياة",
          "أطرف نكتة تعرفها",
          "مشروع أو هواية تعمل عليها حاليًا",
          "طريقتك المثالية لقضاء يوم كسول",
          "قضية تشغل بالك",
          "آخر شيء جعلك تضحك بصوت عالٍ",
          "هدف وضعته لنفسك هذا العام",
          "طريقتك المفضلة للاسترخاء والتخلص من التوتر",
          "عمل عشوائي من اللطف تعرضت له",
          "فصلك المفضل ولماذا",
          "آخر فيلم جعلك تبكي",
          "فترة تاريخية تجدها مثيرة للاهتمام",
          "نوع المطبخ المفضل لديك",
          "اختراع تعتقد أنه غيّر العالم للأفضل",
          "اقتباسك المفضل وأهميته بالنسبة لك",
          "خوف تغلبت عليه",
          "أفضل حفلة موسيقية أو عرض مباشر حضرته على الإطلاق",
          "وجهتك المثالية لقضاء العطلة",
          "موهبة تمتلكها قد لا يتوقعها الناس",
          "أكثر هدية تذكارية تلقيتها",
          "لغة تود تعلمها",
          "نوع الطقس المفضل لديك",
          "عنصر في قائمة أمنياتك",
          "أفضل وجبة تناولتها على الإطلاق",
          "كتاب أو فيلم جعلك تفكر بشكل مختلف",
          "فنان أو فرقة تحبها وقد لا يعرفها معظم الناس",
          "نشاط خارجي مفضل",
          "لغز أو لعبة لا يمكنك حلها ولكنك تتمنى لو كنت تستطيع",
          "أكثر درس تأثيرًا تعلمته من خطأ",
          "عادة تحاول التخلص منها أو تطويرها",
          "طريقتك المفضلة للاحتفال بإنجاز",
          "قطعة تقنية لا يمكنك العيش بدونها",
          "مهارة أو حيلة حفلة غير عادية يمكنك أداؤها",
          "أكثر مكان مثير للاهتمام استكشفته على الإطلاق",
          "كتابك المفضل من الطفولة",
          "هواية اكتسبتها خلال الحجر الصحي",
          "أصعب شيء في النمو",
          "بودكاستك المفضل ولماذا",
          "إنجاز تفتخر به",
          "أفضل نصيحة حياتية تلقيتها على الإطلاق",
          "حقيقة عشوائية تجدها مثيرة للاهتمام",
          "أكثر شيء مؤثر شهدته",
          "لعبة الطاولة أو لعبة الورق المفضلة للعب مع الأصدقاء",
          "قاعدة شخصية لا تخرقها أبدًا",
          "آخر عمل خيري قمت به",
          "فيلم يجعلك تشعر بالراحة دائمًا",
          "مكانك المفضل للهروب إليه عندما تحتاج إلى السلام",
          "موضوع تتمنى أن تعرف المزيد عنه",
          "أغرب طعام جربته",
          "طريقتك المفضلة لقضاء الوقت مع العائلة",

],
        Ko: ["슈퍼맨 대 배트맨: 당신은 어느 쪽이 되고 싶습니까?","불을 뿜는 능력 대 물건을 얼리는 능력",
        "날 수 있는 능력 대 투명해질 수 있는 능력",
        "초능력을 얻었다면, 그것을 비밀로 지킬 수 있겠습니까?",
        "외모를 바꿀 수 있는 능력 대 돈을 만들 수 있는 능력",
        "친구들이 당신의 초능력을 알게 된다면 어떻게 할 것입니까?",
        "다음에 AI가 인수할 것으로 생각하는 직업은 무엇입니까?",
        "AI가 구동하는 차를 타고 싶습니까?",
        "당신을 위해 AI가 할 수 있기를 바라는 집안일은 무엇입니까?",
        "말만으로 게임 속 세계를 창조할 수 있다면, 무엇이라고 말하겠습니까?",
        "AI의 미래에 대해 어떻게 생각하십니까?",
        "온라인 친구가 미래에서 온 AI로 밝혀진다면, 그 친구와의 관계를 계속 이어가겠습니까?",
        "가장 좋아하는 애니메이션 노래",
        "가장 좋아하는 애니메이션",
        "기억에서 그릴 수 있는 애니메이션 캐릭터",
        "되고 싶은 애니메이션 캐릭터",
        "처음 본 애니메이션",
        "자유롭게 애니메이션을 만들 수 있다면, 어떤 종류의 애니메이션이 될까요?",
        "가장 좋아하는 보드 게임",
        "보드 게임을 소유하고 있습니까?",
        "잘하거나 어려워하는 보드 게임",
        "보드 게임을 만든다면, 어떤 게임이 될까요?",
        "모든 소유물을 잃는 것이 패배를 의미하지만 승리하면 부자가 되는 게임에 참여하겠습니까?",
        "보드 게임과 관련된 추억",
        "추천하는 책",
        "더 자주 읽는 것은? 만화 대 소설",
        "당신에게 가장 큰 영향을 준 책",
        "영화나 애니메이션으로 만들기를 바라는 소설이나 만화",
        "책을 쓴다면, 어떤 종류의 책이 될까요?",
        "종이책이 사라져야 한다고 생각하십니까?",
        "좋아하는 자동차 종류는 무엇입니까?",
        "지금까지 본 가장 비싼 자동차",
        "운전을 잘하십니까?",
        "세계에서 가장 강력한 자동차를 만든다면, 어떤 모습일까요?",
        "자동차를 선택할 때 중요한 것은: 가격, 안전, 브랜드?",
        "100년 후 자동차에 어떤 기능이 있을 것이라고 생각하십니까?",
        "고양이가 될 수 있다면 무엇을 하고 싶습니까?",
        "고양이를 입양한다면 어떤 품종을 선택하겠습니까?",
        "고양이 언어를 이해하는 것 대 고양이를 마음대로 조종하는 것",
        "이야기 속에서 가장 좋아하는 고양이",
        "이상적인 고양이 카페를 어떻게 디자인하겠습니까?",
        "너무 귀여운 길고양이를 발견했다면 어떻게 하겠습니까?",
        "받은 크리스마스 선물에 대해 이야기해주세요",
        "산타클로스나 순록 중 하나가 될 수 있다면 어느 쪽을 선택하겠습니까?",
        "크리스마스에 무엇을 먹습니까?",
        "추천하는 크리스마스 영화",
        "올해 크리스마스는 어떻게 보낼 계획입니까?",
        "크리스마스의 추억",
        "가장 좋아하는 의류 브랜드",
        "가장 좋아하는 패션 조합",
        "자주 모자를 쓰십니까?",
        "단순한 패턴 대 화려한 패턴",
        "전 파트너가 준 옷을 입을 수 있습니까?",
        "버릴 수 없는 옷과 그 기억",
        "숫자나 음악 노트를 생각할 때 색상이나 냄새를 느낀 적이 있습니까?",
        "오직 다섯 가지 크레용 색상만 선택할 수 있다면, 어떤 색을 고르겠습니까?",
        "현재 기분을 대표하는 색은 무엇입니까?",
        "가장 좋아하는 색상",
        "모든 음식이 파란색이나 빨간색으로 바뀐다면, 어느 색을 선택하겠습니까?",
        "자주 입는 옷의 색상은 무엇입니까?",
        "최근에 한 친환경적인 일은 무엇입니까?",
        "쇼핑할 때 환경을 고려하십니까?",
        "자동차보다 기차를 선호하십니까?",
        "쓰레기 분리수거에 신경 쓰십니까?",
        "쓰레기 줍기에 참여한 적이 있습니까?",
        "당신의 도시를 깨끗하다고 생각하십니까?",
        "다이어트를 해 본 적이 있습니까?",
        "싫어하는 음식",
        "가장 좋아하는 단 것",
        "너무 많이 먹는 음식",
        "추천하는 식당",
        "맛있는 음식에서 무엇이 더 중요합니까? 맛, 위치, 동반자?",
        "가장 좋아하는 게임",
        "가장 좋아하는 게임 장르",
        "버릴 수 없는 게임 카트리지가 있습니까?",
        "PC 대 스마트폰",
        "고품질 그래픽의 장점 대 32비트 게임의 장점",
        "게임에서 더 중요한 것은: 경험인가 스토리인가?",
        "할로윈을 생각할 때, 떠오르는 캐릭터는?",
        "할로윈에 코스프레하고 싶은 캐릭터",
        "일본과 해외의 할로윈 문화 차이에 대한 생각",
        "잭 오 랜턴을 만들어 본 적이 있습니까?",
        "할로윈을 보내는 추천 방법",
        "끝없는 사탕을 얻을 수 있다면, 얼마나 원하십니까?",
        "당신의 취미",
        "친구나 가족에게 자주 경고받는 것",
        "막 만난 사람에게 자기 소개를 해보세요",
        "어렸을 때 싫어했지만 지금은 먹을 수 있는 것",
        "시간을 보내는 가장 좋아하는 방법",
        "당신마저 이상하다고 생각하는 특이한 습관",
        "가장 좋아하는 악기",
        "게임에서 추천하는 음악 이벤트",
        "가장 좋아하는 노래",
        "비 오는 날 듣기 좋아하는 노래",
        "특별한 추억이 있는 노래",
        "게임에서 추천하는 가수",
        "새해를 보내는 가장 좋아하는 방법",
        "가족의 독특한 새해 전통",
        "지난해 새해의 추억",
        "당신의 나라에서 새해를 어떻게 축하합니까?",
        "새해가 오면 항상 하는 일",
        "작년에 세운 새해 결심은 무엇입니까?",
        "가장 좋아하는 그림",
        "유명한 그림을 본 적이 있습니까?",
        "디지털 대 아날로그 선호?",
        "추천하는 미술관",
        "가장 좋아하는 역사적 화가",
        "비싼 그림을 구입한 적이 있습니까?",
        "고급 그래픽 카드가 있습니까?",
        "첫 PC 구입",
        "맥, 윈도우, 아니면 다른 것?",
        "외관 대 고기능성",
        "멀티 디스플레이 설정이 있습니까?",
        "무료로 받을 수 있다면, 고급 게이밍 마우스 대 고급 게이밍 의자 중 어느 것을 선택하겠습니까?",
        "보통 고백을 받습니까, 아니면 고백합니까?",
        "학생-교사 관계가 작동할 수 있습니까?",
        "파트너를 선택할 때 최종 결정권은: 이성인가 직관인가?",
        "장거리 관계 대 연령 차이 관계",
        "사랑에서 언어 장벽이 될 수 있습니까?",
        "이상적인 파트너",
        "존경하는 사람",
        "존경하는 역사적 인물",
        "가장 좋아하는 속담",
        "존경하는 사람 유형",
        "최근 누군가의 행동에 감동받은 것",
        "되고 싶은 사람의 종류",
        "바다와 산 중 어느 것을 더 선호하십니까?",
        "서핑을 해 본 적이 있습니까?",
        "바다에서 겪은 사고",
        "수영을 잘하십니까?",
        "더 매력적인 능력은: 세계 최고의 장거리 수영 선수 대 세계 최고의 프리 다이버",
        "바다의 추억",
        "지금까지 잤던 가장 긴 시간",
        "가장 이상한 악몽",
        "가장 오래 깨어 있던 시간",
        "무인도에 베개나 담요 중 하나만 가져갈 수 있다면, 어느 것을 선택하겠습니까?",
        "수업 중에 잠든 적이 있습니까?",
        "지나치게 잠든 이야기",
        "갑자기 10,000개 이상의 좋아요를 받은 게시물은 무엇입니까?",
        "유명인에게 좋아요를 받은 적이 있습니까?",
        "팔로우하는 사람이 팔로워보다 많습니까?",
        "인스타그램 대 트위터",
        "과거에 사용했던 인터넷 서비스",
        "미래의 소셜 네트워크가 어떻게 될 것이라고 생각하십니까?",
        "가장 좋아하는 인형은 무엇입니까?",
        "인형이 말할 수 있다면, 무엇이라고 말할 것 같습니까?",
        "게임 아바타를 인형으로 가질 수 있다면, 어떤 것을 선택하겠습니까?",
        "오늘 당신의 방에 인형을 하나 추가할 수 있다면, 무엇이 될까요?",
        "두 동물을 섞어 귀여운 인형을 만들 수 있다면, 어떤 것을 섞겠습니까?",
        "인형 만들기가 당신의 일이라면, 무엇을 만들겠습니까?",
        "몸의 어느 부분에 성형 수술을 할 수 있다면, 무엇을 바꾸겠습니까?",
        "쌍꺼풀이 있는 것과 없는 것 중 어느 것을 선호하십니까?",
        "제거하고 싶은 문신이 있습니까?",
        "다른 사람들이 이해하지 못할 수도 있는 자신의 몸에 대해 자각하는 부분",
        "하루 동안 아바타처럼 인종이나 성별을 바꿀 수 있다면, 무엇을 선택하겠습니까?",
        "10년 젊어 보이게 하는 알약 대 10년 더 건강하게 하는 알약",
        "가장 좋아하는 사탕",
        "무제한으로 접근할 수 있는 한 가지 사탕이 있다면, 무엇이 될까요?",
        "직접 만든 사탕",
        "300달러짜리 비싼 사탕 대 1달러짜리 사탕 300개",
        "싫어하는 사탕",
        "사탕에서 더 중요한 것은: 외모, 맛, 가격?",
        "해외 여행의 추억",
        "여름에 차가운 나라로 갈 수 있다면, 어디로 가고 싶습니까?",
        "어느 나라로 순간 이동하고 싶습니까?",
        "더 도전적인 것은: 배 대 비행기",
        "시도해 보고 싶은 외국 요리",
        "세계의 역사적 건물을 보고 싶습니까?",
        "추천하는 유튜버",
        "최근에 웃긴 비디오",
        "의도치 않게 보게 되는 비디오",
        "언어 학습에 추천하는 비디오",
        "자주 보는 비디오 장르",
        "싫어하는 비디오 유형",
        "배우나 성우가 되고 싶습니까?",
        "가장 좋아하는 배우/성우",
        "할리우드 영화에서 역할을 맡게 된다면, 어떤 캐릭터를 연기하고 싶습니까?",
        "하루 동안 유명한 배우/성우가 될 수 있다면, 무엇을 하겠습니까?",
        "3D 캐릭터의 모션 액터가 될 수 있다면, 어떤 캐릭터를 연기하고 싶습니까?",
        "잘하는 인상을 보여주세요!",
        "목욕을 빨리 하십니까?",
        "개인적으로 사용하는 샴푸가 있습니까?",
        "가보고 싶은 온천이 있습니까?",
        "여행할 때 바디 소프나 샴푸 중 하나를 집에 두고 가야 한다면, 어느 것을 선택하겠습니까?",
        "뜨거운 물에 애를 먹습니까?",
        "사우나에서 얼마나 버틸 수 있습니까?",
        "캠핑을 해 본 적이 있습니까?",
        "텐트에서 잔 적이 있습니까?",
        "바비큐에 대한 추억",
        "트리하우스에서 살고 싶습니까?",
        "혼자 캠핑을 해보고 싶습니까?",
        "캠프 음식을 생각하면 무엇이 떠오릅니까?",
        "최근에 울게 만든 사건",
        "쉽게 우는 편입니까?",
        "음식이 너무 매워서 운 적이 있습니까?",
        "1분 안에 울 수 있습니까?",
        "울게 만드는 영화",
        "너무 아파서 울게 만든 이야기",
        "최근에 실망스러운 것",
        "희망이 없다고 느끼는 것",
        "당신의 의견으로 최악의 죽음 방법",
        "세상에 대해 절망하게 만드는 것",
        "더 절망적인 것은: 밖에 있을 때 휴대폰 배터리가 다 되거나 휴대폰을 잊어버린 것",
        "더 나쁜 것은: 가까운 친구에게 잊혀지는 것 대 싫어하는 사람을 만나는 것",
        "부자가 되기 위해 무엇을 희생하겠습니까?",
        "어린 시절의 꿈",
        "만나고 싶은 사람",
        "시도해 보고 싶은 호화로운 음식",
        "이상적인 생활 방식",
        "습득하고 싶은 기술",
        "가장 잘하는 과목은 무엇입니까?",
        "싫어하는 음식은?",
        "누구에게도 지지 않는다고 믿는 기술",
        "잘하는 것과 못하는 것 중 무엇을 먼저 끝내고 싶습니까?",
        "구입했지만 아직 읽지 않은 책이 있습니까?",
        "불편한 장소는 어디입니까?",
        "행복이란 무엇을 의미합니까?",
        "행복 수준이 1에서 10까지 있다면, 1단계 음식은 무엇입니까?",
        "조용함과 소음 중 어느 것이 더 행복을 가져다줍니까?",
        "당신만의 독특한 행복은 무엇입니까?",
        "부와 행복의 차이",
        "당신의 생각에 세계에서 가장 행복한 동물은?",
        "고향의 특산품은 무엇입니까?",
        "고향의 추억",
        "고향의 관광 명소",
        "고향 출신의 유명인이 있습니까?",
        "아직도 고향에 살고 있습니까?",
        "동창회에 참석한 적이 있습니까?",
        "마지막으로 한 거짓말",
        "자신을 정직한 사람이라고 생각하십니까?",
        "한 명의 거짓말쟁이가 있는 방 대 모두가 거짓말을 하는 방",
        "믿을 만한 거짓말을 해보세요",
        "거짓말처럼 들리는 진짜 이야기",
        "어느 정도의 거짓말을 용납할 수 있습니까?",
        "결혼식에 간 적이 있습니까?",
        "이상적인 결혼 생활",
        "이상적인 결혼 상대",
        "이상적인 커플을 알고 있습니까?",
        "자녀가 있는 사람과 결혼할 수 있습니까?",
        "결혼한다면 몇 명의 자녀를 갖고 싶습니까?",
        "아침을 보내는 가장 좋아하는 방법",
        "가장 좋아하는 아침 식사",
        "밤에 늦게까지 일어나는 사람입니까, 아침형 인간입니까?",
        "아침에 듣기 좋아하는 음악",
        "매일 아침의 루틴",
        "수면 마비를 경험한 적이 있습니까?",
        "마지막으로 본 영화",
        "추천하는 영화",
        "올해의 상위 3개 영화",
        "매년 보는 영화",
        "원작보다 리메이크가 더 나은 경우가 있습니까?",
        "가장 좋아하는 영화 장르",
        "참을 수 없는 것",
        "앞에 있으면 절대 참을 수 없는 음식",
        "더 참을 수 없는 것: 기다리다가 서 있거나 빌려준 물건이 팔리는 것",
        "플래시 몹에서 프러포즈를 받았다면 어떻게 할 것입니까?",
        "가족이나 친구에 대한 나쁜 말을 듣는 것을 참을 수 있습니까?",
        "최근에 화가 난 것",
        "애완동물이 있습니까?",
        "키운 애완동물은 무엇입니까?",
        "애완동물의 나이는 얼마입니까?",
        "애완동물 가게를 폐지해야 한다고 생각하십니까?",
        "세계의 어떤 동물이라도 애완동물로 가질 수 있다면, 무엇을 선택하겠습니까?",
        "애완동물로 가지고 싶은 가상의 동물",
        "가장 좋아하는 식물",
        "공원에서 자주 나뭇잎이나 꽃, 씨앗을 줍습니까?",
        "키우고 있는 식물이 있습니까?",
        "직접 재배하고 먹은 과일이나 채소가 있습니까?",
        "독창적인 식물을 만들 수 있다면, 어떤 것이 될까요?",
        "가장 좋아하는 꽃",
        "어렸을 때 많이 했던 게임",
        "당신의 지역에서만 인기 있는 게임",
        "학교에서 많이 했던 게임",
        "어렸을 때 갖고 싶었지만 살 수 없었던 장난감이나 게임",
        "추천하는 카드 게임",
        "숨바꼭질을 잘하십니까?",
        "돈을 저축하고 있습니까?",
        "자신을 절약하는 사람이라고 생각하십니까, 아니면 지출하는 사람입니까?",
        "비밀 저축 팁이 있다면 공유해주세요",
        "더 중요한 것은: 돈인가 경험인가?",
        "냉동 식품 무제한 대 신선한 채소 무제한: 어느 것이 더 사치스러운가?",
        "전기 없이 한 달 대 물 없이 한 달",
        "흡연을 하십니까? 아니라면, 왜 안 하십니까?",
        "성공적으로 금연한 사람을 알고 있습니까?",
        "흡연이 건강에 해롭다고 생각하십니까?",
        "전자 담배에 대한 생각은 어떻습니까?",
        "하루에 몇 개비를 피우면 많이 피우는 것으로 간주합니까?",
        "시가를 피워 본 적이 있습니까?",
        "가장 좋아하는 스포츠",
        "응원하지 않을 수 없는 스포츠 팀이 있습니까?",
        "가장 좋아하는 운동선수",
        "아직 시도해 보지 않은 스포츠",
        "규칙을 완전히 이해하지 못하는 스포츠",
        "e스포츠가 올림픽 종목이 되어야 한다고 생각하십니까?",
        "새로운 휴일을 만들 수 있다면, 어떤 것이 될까요?",
        "어린 시절 가장 좋아하는 추억",
        "지금까지 마주친 가장 어려운 퍼즐이나 게임",
        "존재하기를 바라는 기술",
        "지금까지 본 가장 흥미로운 다큐멘터리",
        "어떤 가상 캐릭터와 저녁을 먹을 수 있다면, 누구를 선택하겠습니까?",
        "받은 가장 좋은 조언",
        "내년에 배우고 싶은 기술",
        "가장 좋아하는 전통이나 축제",
        "지금까지 방문한 가장 아름다운 장소",
        "인생에 대한 관점을 바꾼 책",
        "알고 있는 가장 재미있는 농담",
        "현재 진행 중인 프로젝트나 취미",
        "게으른 날을 보내는 이상적인 방법",
        "열정을 갖고 있는 원인",
        "큰소리로 웃게 만든 마지막 일",
        "올해 자신에게 설정한 목표",
        "휴식과 이완을 위한 가장 좋아하는 방법",
        "경험한 무작위 친절한 행동",
        "가장 좋아하는 계절과 그 이유",
        "울게 만든 마지막 영화",
        "흥미로운 역사적 시대",
        "가장 좋아하는 요리 유형",
        "세상을 더 나은 곳으로 만든 것으로 생각하는 발명품",
        "가장 좋아하는 인용구와 그것이 당신에게 가지는 의미",
        "극복한 두려움",
        "지금까지 본 가장 좋은 콘서트나 라이브 공연",
        "꿈의 휴가 목적지",
        "사람들이 예상치 못할 당신이 가진 재능",
        "지금까지 받은 가장 기억에 남는 선물",
        "배우고 싶은 언어",
        "가장 좋아하는 날씨 유형",
        "버킷리스트에 있는 항목",
        "지금까지 먹어본 최고의 식사",
        "생각을 달리하게 만든 책이나 영화",
        "대부분의 사람들이 들어보지 못한 당신이 사랑하는 아티스트나 밴드",
        "가장 좋아하는 야외 활동",
        "풀지 못하지만 풀고 싶은 퍼즐이나 게임",
        "실수에서 배운 가장 영향력 있는 교훈",
        "버리거나 개발하려는 습관",
        "성취를 축하하는 가장 좋아하는 방법",
        "없이는 살 수 없는 기술 제품",
        "수행할 수 있는 특이한 기술이나 파티 트릭",
        "지금까지 탐험한 가장 흥미로운 장소",
        "어린 시절 가장 좋아했던 책",
        "격리 중에 시작한 취미",
        "성장하는 것에 대해 가장 어려운 점",
        "가장 좋아하는 팟캐스트와 그 이유",
        "자랑스러워하는 성취",
        "받은 가장 좋은 인생 조언",
        "흥미롭게 생각하는 무작위 사실",
        "목격한 가장 마음을 따뜻하게 하는 일",
        "친구들과 함께 하는 가장 좋아하는 보드 게임이나 카드 게임",
        "절대 어기지 않는 개인적인 규칙",
        "마지막으로 한 선행",
        "항상 기분을 좋게 만드는 영화",
        "평화가 필요할 때 도피처로 가는 가장 좋아하는 장소",
        "더 알고 싶은 주제",
        "지금까지 먹어본 가장 이상한 음식",
        "가족과 함께 시간을 보내는 가장 좋아하는 방법",


]


    };
    let currentLanguage = 'en'; // 初期言語設定

    const languageToggle = document.getElementById('languageToggle');
    const generateButton = document.getElementById('generateButton');
    const promptDisplay = document.getElementById('promptDisplay');


        languageSelect.addEventListener('change', () => {
            // 選択されたオプションの値に基づいて言語を切り替える
            currentLanguage = languageSelect.value;
        });

        generateButton.addEventListener('click', () => {
            let intervalTime = 50;
            const maxIntervalTime = 300;
            const intervalIncrease = 25;
            const selectedPrompts = prompts[currentLanguage];

            const changePrompt = () => {
                promptDisplay.textContent = selectedPrompts[Math.floor(Math.random() * selectedPrompts.length)];
                if (intervalTime < maxIntervalTime) {
                    intervalTime += intervalIncrease;
                    setTimeout(changePrompt, intervalTime);
                }
            };

            setTimeout(changePrompt, intervalTime);
        });
    });
