document.addEventListener('DOMContentLoaded', () => {
    const prompts = {
        en: [
          "Superman vs Batman: Which one would you want to be?",
          "Ability to breathe fire vs Ability to freeze things",
          "Ability to fly vs Ability to become invisible",
          "If you acquired a superpower, could you keep it a secret?",
          "Ability to change your appearance vs Ability to produce money",
          "What would you do if your friends found out about your superpower?",
          "What job do you think AI will take over next?",
          "Would you like to ride in an AI-powered car?",
          "A chore you wish AI could do for you.",
          "If you could create a world in Games just by speaking, what would you say?",
          "What do you think the future of AI will be like?",
          "If your online friend turned out to be an AI from the future, would you continue the friendship?",
          "Favorite anime song",
          "Favorite anime",
          "An anime character you can draw from memory",
          "Anime character you'd like to become",
          "The first anime you watched",
          "If you could freely create an anime, what kind of anime would it be?",
          "Favorite board game",
          "Do you own any board games?",
          "Board games you are good at or struggle with",
          "If you were to create a board game, what would it be like?",
          "Would you participate in a game where losing means losing all your possessions, but winning makes you rich?",
          "Memories related to board games",
          "Recommended book",
          "Which do you read more often? Manga vs Novels",
          "The book that influenced you the most",
          "A novel or manga you wish to be made into a movie or anime",
          "If you were to write a book, what kind of book would it be?",
          "Do you think physical books should become obsolete?",
          "What kind of car do you like?",
          "The most expensive car you've ever seen",
          "Are you good at driving?",
          "If you could create the world's strongest car, what would it be like?",
          "What do you look for in a car: Price, safety, or brand?",
          "What features do you think cars will have in 100 years?",
          "If you could become a cat, what would you want to do?",
          "If you were to get a cat, what breed would you choose?",
          "Understand cat language vs Control cats at will",
          "Favorite cat from a story",
          "How would you design your ideal cat cafe?",
          "What would you do if you found an excessively cute stray cat?",
          "Talk about a Christmas gift you received",
          "If you could become either Santa Claus or a reindeer, which would you choose?",
          "What do you eat for Christmas?",
          "Recommended Christmas movie",
          "How will you spend Christmas this year?",
          "Memories of Christmas",      "Favorite clothing brand",
          "Favorite fashion coordination",
          "Do you often wear hats?",
          "Plain vs flashy patterns",
          "Can you wear clothes given to you by an ex-partner?",
          "An item of clothing you can't throw away and its memory",
          "Do you ever perceive colors or smells when thinking about numbers or musical notes?",
          "If you could only choose five crayon colors, which would you pick?",
          "What color represents your current mood?",
          "Favorite color",
          "If all food turned either blue or red, which would you choose?",
          "What color clothes do you wear often?",
          "What environmentally friendly thing have you done recently?",
          "Do you consider the environment when shopping?",
          "Preference for trains over cars",
          "Do you pay attention to sorting garbage?",
          "Have you ever gone on a trash pickup?",
          "Do you think your town is clean?",
          "Have you ever tried a diet?",
          "Food you dislike",
          "Favorite sweets",
          "Something you eat too much of",
          "Recommended restaurant",
          "In delicious food, what's more important: Taste, location, or company?",
          "Favorite game",
          "Favorite game genre",
          "Do you have any game cartridges you can't throw away?",
          "PC vs Smartphone",
          "Pros of high-quality graphics in games vs Pros of 32-bit games",
          "In gaming, what's more important: Experience or story?",
          "When you think of Halloween, which character comes to mind?",
          "A character you'd like to cosplay for Halloween",
          "Your thoughts on the differences between Halloween culture in Japan and abroad",
          "Have you ever made a Jack-o'-lantern?",
          "Recommended ways to spend Halloween",
          "If you could get endless candy, how much would you want?",
          "Your hobby",
          "Something you're often warned about by friends or family",
          "Introduce yourself to someone you've just met",
          "Something you disliked as a child but can eat now",
          "Your favorite way to spend time",
          "A peculiar habit of yours that even you think is strange",
          "Favorite musical instrument",
          "Recommended music event in Games",
          "Favorite song",
          "Song you like to listen to on rainy days",
          "Song with special memories",
          "Recommended singer in Games",
          "Favorite way to spend New Year",
          "A unique New Year tradition in your family",
          "Memories of last year's New Year",
          "How your country celebrates New Year",
          "Something you always do when the New Year arrives",
          "What was your New Year's resolution last year?",
          "Favorite painting",
          "Have you seen any famous paintings?",
          "Preference: Digital or analog?",
          "Recommended art museum",
          "Favorite historical painter",
          "Have you ever bought an expensive painting?",
          "Do you have a high-end graphics card?",
          "Your first PC purchase",
          "Mac, Windows, or other?",
          "Appearance vs High functionality",
          "Do you have a multi-display setup?",
          "If you could receive one for free, which would you choose: high-end gaming mouse vs high-end gaming chair?",
          "Are you usually confessed to, or do you confess?",
          "Can a student-teacher relationship work?",
          "Who has the final say in choosing a partner: Rationality or intuition?",
          "Long-distance relationship vs Age-gap relationship",
          "Can language be a barrier in love?",
          "Your ideal partner",
          "A person you admire",
          "A historical figure you respect",
          "Favorite proverb",
          "The type of person you respect",
          "A recent action by someone that moved you",
          "The kind of person you aspire to be",
          "Do you prefer the sea or the mountains?",
          "Have you ever surfed?",
          "A mishap you had at the sea",
          "Are you good at swimming?",
          "Which ability is more appealing: World's best long-distance swimmer vs World's best free diver",
          "Memories of the sea",
          "The longest you've ever slept",
          "The strangest nightmare you've had",
          "The longest you've stayed awake",
          "If you could only bring a pillow or blanket to a deserted island, which would you choose?",
          "Have you ever slept in class?",
          "A story about oversleeping",
          "What was your post about that received over 10,000 likes suddenly?",
          "Have you ever had a post liked by a celebrity?",
          "Do you follow more people than you have followers?",
          "Instagram over Twitter",
          "An internet service you used in the past",
          "What do you think future social networks will be like?",
          "What is your favorite stuffed animal?",
          "If your stuffed animal could talk, what do you think it would say?",
          "If you could have a Games avatar as a stuffed animal, which would you choose?",
          "If you could add one stuffed animal to your room today, what would it be?",
          "If you could create a cute stuffed animal by mixing two animals, what would you mix?",
          "If making stuffed animals was your job, what would you make?",
          "If you could have plastic surgery on any part of your body, what would you change?",
          "Do you prefer double eyelids or single eyelids?",
          "Do you have a tattoo you want to remove?",
          "A part of your body that you feel self-conscious about that others might not understand",
          "If you could change your race or gender for a day like changing an avatar, what would you choose?",
          "A pill that makes you look 10 years younger vs A pill that makes you 10 years healthier",
          "Favorite candy",
          "If you could have unlimited access to one candy, what would it be?",
          "Candy you've made yourself",
          "Expensive $300 candy vs 300 pieces of $1 candy",
          "Candy you dislike",
          "In candy, what's more important: Appearance, taste, or price?",
          "Memories of an overseas trip",
          "If you could go to a cold country in summer, where would you like to go?",
          "If you could teleport to any country, which would you choose?",
          "Which do you find more challenging: boats or airplanes?",
          "A foreign dish you want to try",
          "A historic building in the world you want to see",
          "Recommended YouTuber",
          "A video that recently made you laugh",
          "Videos you end up watching unintentionally",
          "Recommended videos for language learning",
          "Your frequently watched video genre",
          "Video type you dislike",
          "Would you like to become an actor or voice actor?",
          "Favorite actor/voice actor",
          "If you got a role in a Hollywood movie, what character would you play?",
          "If you could be a famous actor/voice actor for a day, what would you do?",
          "If you could be a motion actor for a 3D character, what kind of character would you like to play?",
          "Show us an impression you're good at!",
          "Are you quick to take baths?",
          "Do you have a personal shampoo?",
          "Is there a hot spring you want to visit?",
          "If you had to leave either body soap or shampoo at home when traveling, which would you choose?",
          "Do you struggle with hot water?",
          "How long can you endure in a sauna?",
          "Have you ever gone camping?",
          "Have you slept in a tent?",
          "Memories of a BBQ",
          "Would you like to live in a treehouse?",
          "Would you like to try solo camping?",
          "What comes to mind when you think of camp food?",
          "A recent incident that made you cry",
          "Are you someone who cries easily?",
          "Have you ever cried because food was too spicy?",
          "Can you cry on command within a minute?",
          "A movie that makes you cry",
          "A story about something so painful it made you cry",
          "Something that recently disappointed you",
          "Something you find hopeless",
          "The worst way to die, in your opinion",
          "Something about the world that makes you despair",
          "Which is more despairing: Your phone battery dying when you're out or forgetting your phone?",
          "What's worse: Being forgotten by a close friend or running into someone you dislike?",
          "What would you sacrifice to become rich?",
          "Childhood dream",
          "Someone you'd like to meet",
          "A luxurious food you want to try",
          "Your ideal lifestyle",
          "A skill you want to acquire",
          "What is your best subject?",
          "A food you dislike?",
          "A skill you believe you're unbeatable at",
          "Do you prefer to finish things you're good at or bad at first?",
          "Do you have any books you bought but haven't finished reading?",
          "A place you find uncomfortable?",
          "What does happiness mean to you?",
          "If happiness levels ranged from 1 to 10, what food would be level 1?",
          "Quietness or noise, which brings you more happiness?",
          "A personal happiness you think might be unique to you",
          "The difference between wealth and happiness",
          "The happiest animal in the world, in your opinion",
          "What is a specialty of your hometown?",
          "Memories of your hometown",
          "Tourist attractions in your hometown",
          "Any famous people from your hometown?",
          "Do you still live in your hometown?",
          "Have you ever had a class reunion?",
          "The last lie you told",
          "Do you consider yourself a truthful person?",
          "A room with one liar vs a room where everyone lies",
          "Tell a believable lie",
          "A true story that sounds like a lie",
          "What level of lie can you tolerate?",
          "Have you been to a wedding?",
          "Your ideal married life",
          "Your ideal marriage partner",
          "Do you know of an ideal couple?",
          "Would you marry someone with children?",
          "How many children would you like to have if you got married?",
          "Your favorite way to spend the morning",
          "Your favorite breakfast",
          "Are you a night owl or an early bird?",
          "Music you like to listen to in the morning",
          "A daily morning routine",
          "Have you ever experienced sleep paralysis?",
          "The last movie you watched",
          "Movie recommendation",
          "Top 3 movies of the year",
          "A movie you watch every year",
          "Has a remake ever been better than the original?",
          "Favorite movie genre",
          "Something you can't tolerate",
          "Food you can't resist if it's in front of you",
          "Which can't you tolerate more: Being stood up or having something you lent sold?",
          "What would you do if you were proposed to in a flash mob?",
          "Can you tolerate hearing bad things about your family or friends?",
          "Something that angered you recently",
          "Do you have a pet?",
          "What pets have you had?",
          "How old is your pet?",
          "Should pet shops be abolished?",
          "If you could have any animal in the world as a pet, what would it be?",
          "A fictional animal you'd like as a pet",
          "Favorite plant",
          "Do you often pick up leaves, flowers, or seeds in the park?",
          "Do you have any plants you are growing?",
          "Have you grown and eaten your own fruits or vegetables?",
          "If you could create an original plant, what would it be?",
          "Favorite flower",
          "What games did you play a lot as a child?",
          "A game popular only in your area",
          "Games you played a lot at school",
          "A toy or game you wanted as a child but couldn't afford",
          "Recommended card game",
          "Are you good at hide and seek?",
          "Are you saving money?",
          "Do you consider yourself frugal or a spender?",
          "If you have a secret saving tip, please share",
          "What's more important: Money or experiences?",
          "Unlimited frozen food vs Unlimited fresh vegetables: Which is more luxurious?",
          "A month without electricity vs A month without water",
          "Do you smoke? If not, why?",
          "Do you know someone who successfully quit smoking?",
          "Do you think smoking is harmful to health?",
          "What are your thoughts on electronic cigarettes?",
          "How many cigarettes a day makes someone a heavy smoker?",
          "Have you ever smoked a cigar?",
          "Favorite sport",
          "Is there a sports team you can't help but support?",
          "Favorite athlete",
          "A sport you haven't tried yet",
          "A sport whose rules you don't fully understand",
          "Do you think eSports should be an Olympic sport?",
          "If you could invent a new holiday, what would it be?",
          "Your favorite childhood memory",
          "The most challenging puzzle or game you've ever faced",
          "A technology you wish existed",
          "The most interesting documentary you've ever watched",
          "If you could have dinner with any fictional character, who would it be?",
          "The best advice you've ever received",
          "A skill you'd like to learn in the next year",
          "Your favorite tradition or celebration",
          "The most beautiful place you've ever visited",
          "A book that changed your perspective on life",
          "The funniest joke you know",
          "A project or hobby you're currently working on",
          "Your ideal way to spend a lazy day",
          "A cause you are passionate about",
          "The last thing that made you laugh out loud",
          "A goal you've set for yourself this year",
          "Your favorite way to relax and unwind",
          "A random act of kindness you've experienced",
          "Your favorite season and why",
          "The last movie that made you cry",
          "A historical period you find fascinating",
          "Your favorite type of cuisine",
          "An invention you think has changed the world for the better",
          "Your favorite quote and its significance to you",
          "A fear you've overcome",
          "The best concert or live performance you've ever attended",
          "Your dream vacation destination",
          "A talent you possess that people might not expect",
          "The most memorable gift you've ever received",
          "A language you'd love to learn",
          "Your favorite type of weather",
          "An item on your bucket list",
          "The best meal you've ever had",
          "A book or movie that made you think differently",
          "An artist or band you love that most people haven't heard of",
          "Your favorite outdoor activity",
          "A puzzle or game that you can't solve but wish you could",
          "The most impactful lesson you learned from a mistake",
          "A habit you're trying to break or develop",
          "Your favorite way to celebrate an accomplishment",
          "A piece of technology you can't live without",
          "An unusual skill or party trick you can perform",
          "The most interesting place you've ever explored",
          "Your favorite childhood book",
          "A hobby you picked up during quarantine",
          "The most challenging thing about growing up",
          "Your favorite podcast and why",
          "An achievement you're proud of",
          "The best piece of life advice you've ever gotten",
          "A random fact you find interesting",
          "The most heartwarming thing you've witnessed",
          "Your favorite board or card game to play with friends",
          "A personal rule you never break",
          "The last good deed you did",
          "A movie that always makes you feel good",
          "Your favorite place to escape to when you need peace",
          "A subject you wish you knew more about",
          "The most unusual food you've ever tried",
          "Your favorite way to spend time with family",
        ],
        ja: [
          "スーパーマン対バットマン：どちらになりたいですか？",
          "火を吹く能力VS物を凍らせる能力",
          "飛ぶ能力VS透明になる能力",
          "もし超能力を手に入れたら、秘密にできますか？",
          "外見を変える能力VSお金を生み出す能力",
          "友人があなたの超能力を知ったら、どうしますか？",
          "AIが次に取って代わると思う仕事は何ですか？",
          "AI駆動の車に乗りたいですか？",
          "AIにやってほしい家事は何ですか？",
          "もし話すだけでゲーム内に世界を作れるとしたら、何と言いますか？",
          "AIの未来はどうなると思いますか？",
          "オンラインの友人が未来から来たAIだったら、その友情を続けますか？",
          "好きなアニメソング",
          "好きなアニメ",
          "記憶から描けるアニメキャラクター",
          "なりたいアニメキャラクター",
          "最初に見たアニメ",
          "自由にアニメを作れるとしたら、どんなアニメにしますか？",
          "好きなボードゲーム",
          "ボードゲームを持っていますか？",
          "得意または苦手なボードゲーム",
          "もしボードゲームを作るなら、どんなものにしますか？",
          "負けたら全財産を失うが、勝てば豊かになれるゲームに参加しますか？",
          "ボードゲームにまつわる思い出",
          "おすすめの本",
          "よく読むのはマンガVS小説どちらですか？",
          "最も影響を受けた本",
          "映画やアニメにしてほしい小説またはマンガ",
          "もし本を書くなら、どんな本にしますか？",
          "紙の本は廃れるべきだと思いますか？",
          "好きな車の種類",
          "今まで見た中で最も高価な車",
          "運転は得意ですか？",
          "世界最強の車を作るとしたら、どんな車にしますか？",
          "車選びで重視するのは価格、安全性、それともブランド？",
          "100年後の車にはどんな機能があると思いますか？",
          "猫になれるとしたら、何をしたいですか？",
          "猫を飼うなら、どの品種を選びますか？",
          "猫の言葉を理解する能力VS猫を自由に操る能力",
          "物語の中の好きな猫",
          "理想の猫カフェのデザインは？",
          "あまりにもかわいい野良猫を見つけたら、どうしますか？",
          "もらったクリスマスプレゼントについて話してください",
          "サンタクロースとトナカイのどちらになりたいですか？",
          "クリスマスに何を食べますか？",
          "おすすめのクリスマス映画",
          "今年のクリスマスはどう過ごしますか？",
          "クリスマスの思い出",
          // この下に残りのプロンプトを翻訳して追加してください...
          "好きな服のブランド",
          "好きなファッションコーディネート",
          "帽子はよくかぶりますか？",
          "シンプルVS派手な柄",
          "元恋人からもらった服を着ますか？",
          "捨てられない服とその思い出",
          "数字や音符を考えるときに色や匂いを感じることがありますか？",
          "もしクレヨンを5色だけ選べるとしたら、どれを選びますか？",
          "現在の気分を表す色は何色ですか？",
          "好きな色",
          "もし全ての食べ物が青色か赤色になるとしたら、どちらを選びますか？",
          "よく着る服の色は何色ですか？",
          "最近した環境に優しいことは何ですか？",
          "買い物をするとき、環境を考慮しますか？",
          "車よりも電車を好む",
          "ゴミの分別に注意していますか？",
          "ゴミ拾いに行ったことがありますか？",
          "あなたの街はきれいだと思いますか？",
          "ダイエットを試みたことがありますか？",
          "苦手な食べ物は？",
          "好きなお菓子",
          "食べ過ぎてしまうもの",
          "おすすめのレストラン",
          "おいしい食べ物において、味、場所、同伴者のどれが重要ですか？",
          "好きなゲーム",
          "好きなゲームジャンル",
          "捨てられないゲームカートリッジがありますか？",
          "PC VS スマートフォン",
          "高品質グラフィックのゲームの長所 VS 32ビットゲームの長所",
          "ゲームにおいて、体験とストーリーのどちらが重要ですか？",
          "ハロウィンと聞いて思い浮かぶキャラクターは？",
          "ハロウィンのためにコスプレしたいキャラクター",
          "日本と海外のハロウィン文化の違いについてどう思いますか？",
          "ジャックオーランタンを作ったことがありますか？",
          "ハロウィンを過ごすおすすめの方法",
          "もし無限にキャンディをもらえるとしたら、どれくらい欲しいですか？",
          "あなたの趣味",
          "友人や家族からよく注意されること",
          "初めて会った人に自己紹介するときに何を言いますか？",
          "子供の頃は嫌いだったけど、今は食べられるもの",
          "好きな過ごし方",
          "自分でも変だと思う変わった習慣",
          "好きな楽器",
          "ゲームでおすすめの音楽イベント",
          "好きな曲",
          "雨の日に聞きたい曲",
          "特別な思い出のある曲",
          "ゲームでおすすめの歌手",
          "お正月の過ごし方",
          "家族独自のお正月の伝統",
          "去年のお正月の思い出",
          "あなたの国のお正月の祝い方",
          "お正月に必ずすること",
          "去年のお正月の抱負は何でしたか？",
          "好きな絵画",
          "有名な絵画を見たことがありますか？",
          "デジタルVSアナログの好み",
          "おすすめの美術館",
          "好きな歴史上の画家",
          "高価な絵画を買ったことがありますか？",
          "高性能グラフィックカードを持っていますか？",
          "最初に購入したPC",
          "Mac、Windows、それともその他？",
          "外見VS高機能性",
          "マルチディスプレイのセットアップを持っていますか？",
          "もし無料で一つもらえるとしたら、高性能ゲーミングマウスと高性能ゲーミングチェアのどちらを選びますか？",
          "普段は告白される方ですか、それとも告白する方ですか？",
          "教師と生徒の関係はうまくいくと思いますか？",
          "パートナー選びで最終的に決めるのは理性か直感か？",
          "遠距離恋愛VS年の差恋愛",
          "言語は恋愛において障壁になり得ますか？",
          "理想のパートナー",
          "尊敬する人",
          "尊敬する歴史上の人物",
          "好きなことわざ",
          "尊敬するタイプの人",
          "最近、誰かの行動に感動しましたか？",
          "目指したい人物像",
          "海と山、どちらが好きですか？",
          "サーフィンをしたことがありますか？",
          "海でのハプニング",
          "泳ぎは得意ですか？",
          "どちらの能力が魅力的ですか？世界最高の長距離泳者VS世界最高のフリーダイバー",
          "海に関する思い出",
          "一番長く寝たことがある時間は？",
          "最も奇妙な悪夢",
          "最も長く起きていた時間",
          "無人島に持って行けるのが枕か毛布のどちらかだったら、どちらを選びますか？",
          "授業中に寝たことがありますか？",
          "寝坊した話",
          "いきなり1万いいねをもらった投稿は何でしたか？",
          "有名人にいいねされたことがありますか？",
          "フォローしている人数よりフォロワーが多いですか？",
          "Instagram VS Twitter",
          "過去に使っていたインターネットサービス",
          "将来のソーシャルネットワークはどうなると思いますか？",
          "好きなぬいぐるみ",
          "もしぬいぐるみが話せるとしたら、何と言うと思いますか？",
          "ゲームのアバターをぬいぐるみにできるとしたら、どれを選びますか？",
          "今日、部屋に一つぬいぐるみを加えるとしたら、何にしますか？",
          "二つの動物を混ぜてかわいいぬいぐるみを作るとしたら、何と何を混ぜますか？",
          "ぬいぐるみを作るのが仕事だったら、何を作りますか？",
          "体のどの部分を整形したいですか？",
          "二重まぶたと一重まぶた、どちらが好みですか？",
          "消したいタトゥーはありますか？",
          "他人には理解しづらいけど、自分がコンプレックスに感じる体の部分",
          "アバターを変えるように一日だけ人種や性別を変えられるとしたら、何を選びますか？",
          "10歳若返る薬と10歳健康になる薬、どちらを選びますか？",
          "好きなキャンディ",
          "一つだけ無限に手に入るキャンディがあるとしたら、何を選びますか？",
          "自分で作ったキャンディ",
          "300ドルの高価なキャンディと1ドルのキャンディ300個、どちらを選びますか？",
          "苦手なキャンディ",
          "キャンディにおいて、見た目、味、価格のどれが重要ですか？",
          "海外旅行の思い出",
          "夏に寒い国へ行くとしたら、どこに行きたいですか？",
          "テレポートでどの国にも行けるとしたら、どこに行きますか？",
          "船と飛行機、どちらが乗りこなすのが難しいと思いますか？",
          "試してみたい外国の料理",
          "世界の歴史的建造物で見たいもの",
          "おすすめのYouTuber",
          "最近笑った動画",
          "意図せず見てしまう動画",
          "言語学習におすすめの動画",
          "よく見る動画のジャンル",
          "苦手な動画のタイプ",
          "俳優または声優になりたいですか？",
          "好きな俳優/声優",
          "ハリウッド映画に出演するなら、どんな役を演じたいですか？",
          "有名な俳優/声優に一日だけなれるとしたら、何をしますか？",
          "3Dキャラクターのモーションアクターになれるとしたら、どんなキャラクターを演じたいですか？",
          "得意な物まねを見せてください！",
          "お風呂は早めに入りますか？",
          "個人的なシャンプーはありますか？",
          "行ってみたい温泉はありますか？",
          "旅行に行くとき、ボディソープとシャンプーのどちらかを家に置いていくとしたら、どちらを選びますか？",
          "お湯が苦手ですか？",
          "サウナでどれくらい耐えられますか？",
          "キャンプに行ったことがありますか？",
          "テントで寝たことがありますか？",
          "BBQの思い出",
          "ツリーハウスに住んでみたいですか？",
          "ソロキャンプを試してみたいですか？",
          "キャンプ食で思い浮かぶもの",
          "最近泣いた出来事",
          "泣きやすいですか？",
          "辛いものを食べて泣いたことがありますか？",
          "1分以内に泣くことができますか？",
          "泣ける映画",
          "痛みで泣いた話",
          "最近失望したこと",
          "絶望的に感じること",
          "あなたにとって最悪の死に方",
          "世界のどこかで絶望を感じさせること",
          "電話のバッテリーが外出中に切れるのと、電話を忘れるのとでは、どちらが絶望的ですか？",
          "親しい友人に忘れられることと、嫌いな人に遭遇すること、どちらが悪いですか？",
          "豊かになるために何を犠牲にしますか？",
          "子供の頃の夢",
          "会いたい人",
          "試してみたい高級な食べ物",
          "理想のライフスタイル",
          "身につけたいスキル",
          "得意な科目は？",
          "苦手な食べ物は？",
          "自分が無敵だと思うスキル",
          "得意なことと苦手なこと、どちらを先に片付けますか？",
          "買ったけどまだ読んでいない本がありますか？",
          "居心地が悪い場所は？",
          "幸福についてどう思いますか？",
          "幸福度が1から10の範囲で、1の食べ物は何ですか？",
          "静けさと騒音、どちらが幸福をもたらしますか？",
          "自分にとってユニークな幸福は何ですか？",
          "富と幸福の違い",
          "世界で最も幸せな動物は何だと思いますか？",
          "故郷の名物は何ですか？",
          "故郷の思い出",
          "故郷の観光名所",
          "故郷の有名人は？",
          "まだ故郷に住んでいますか？",
          "同窓会に行ったことがありますか？",
          "最後についた嘘",
          "自分を正直な人だと思いますか？",
          "嘘つきが一人いる部屋と全員が嘘つきの部屋、どちらがいいですか？",
          "信じられる嘘を教えてください",
          "嘘のように聞こえる本当の話",
          "どのレベルの嘘を許容できますか？",
          "結婚式に行ったことがありますか？",
          "理想の結婚生活",
          "理想の結婚相手",
          "理想的なカップルを知っていますか？",
          "子供がいる人と結婚しますか？",
          "結婚したら何人の子供がほしいですか？",
          "朝の過ごし方",
          "好きな朝食",
          "夜型人間ですか、朝型人間ですか？",
          "朝に聞きたい音楽",
          "毎朝のルーチン",
          "金縛りを経験したことがありますか？",
          "最後に見た映画",
          "映画のおすすめ",
          "今年のトップ3映画",
          "毎年見る映画",
          "リメイクが原作より良かったことがありますか？",
          "好きな映画ジャンル",
          "我慢できないこと",
          "目の前にあったら抵抗できない食べ物",
          "待ち合わせで立ち上げられることと、貸したものを売られること、どちらが我慢できない？",
          "フラッシュモブでプロポーズされたらどうしますか？",
          "家族や友人の悪口を聞くのを我慢できますか？",
          "最近腹を立てたこと",
          "ペットはいますか？",
          "飼ったことのあるペット",
          "ペットの年齢は？",
          "ペットショップは廃止されるべきだと思いますか？",
          "もし世界中のどんな動物でもペットにできるとしたら、何を選びますか？",
          "ペットにしたい架空の動物",
          "好きな植物",
          "公園で葉っぱ、花、種をよく拾いますか？",
          "育てている植物はありますか？",
          "自分で育てて食べた果物や野菜がありますか？",
          "オリジナルの植物を作るとしたら、どんなものにしますか？",
          "好きな花",
          "子供の頃よく遊んだゲーム",
          "地域に特有の人気ゲーム",
          "学校でよく遊んだゲーム",
          "子供の頃欲しかったけど手に入らなかったおもちゃやゲーム",
          "おすすめのカードゲーム",
          "かくれんぼが得意ですか？",
          "お金を貯めていますか？",
          "節約派ですか、浪費派ですか？",
          "秘密の節約ティップがあれば教えてください",
          "お金と経験、どちらが重要ですか？",
          "無制限の冷凍食品対無制限の新鮮な野菜、どちらがより贅沢ですか？",
          "1ヶ月電気がない生活と1ヶ月水がない生活、どちらが厳しいですか？",
          "タバコを吸いますか？吸わないなら、なぜですか？",
          "成功して禁煙した人を知っていますか？",
          "タバコは健康に悪いと思いますか？",
          "電子タバコについてどう思いますか？",
          "1日に何本吸うとヘビースモーカーだと思いますか？",
          "葉巻を吸ったことがありますか？",
          "好きなスポーツ",
          "応援せずにはいられないスポーツチームはありますか？",
          "好きなアスリート",
          "まだ試したことのないスポーツ",
          "ルールを完全に理解していないスポーツ",
          "eスポーツはオリンピック競技になるべきだと思いますか？",
          "新しい祝日を作るとしたら、どんな日にしますか？",
          "子供の頃のお気に入りの思い出",
          "これまで直面した最も難しいパズルやゲーム",
          "存在してほしいと思う技術",
          "今まで見た中で最も興味深いドキュメンタリー",
          "架空のキャラクターと夕食を共にできるとしたら、誰を選びますか？",
          "今までで一番良いアドバイス",
          "来年中に学びたいスキル",
          "好きな伝統や祝日",
          "訪れた中で最も美しい場所",
          "人生観を変えた本",
          "知っている一番面白いジョーク",
          "現在取り組んでいるプロジェクトや趣味",
          "怠ける日を過ごす理想的な方法",
          "情熱を注いでいる原因",
          "大声で笑った最後のこと",
          "今年自分に課した目標",
          "リラックスしてリフレッシュする好きな方法",
          "経験したランダムな親切",
          "好きな季節とその理由",
          "最後に泣かせた映画",
          "魅力的だと思う歴史上の時期",
          "好きな料理の種類",
          "世界をより良い場所に変えたと思う発明",
          "好きな引用とそのあなたにとっての意味",
          "克服した恐怖",
          "参加した中で最高のコンサートやライブパフォーマンス",
          "夢の休暇先",
          "人があまり知らないかもしれないけど持っている才能",
          "今までで最も記憶に残る贈り物",
          "学びたい言語",
          "好きな天気",
          "バケットリストにある項目",
          "今までで最高の食事",
          "考え方を変えた本や映画",
          "ほとんどの人が知らないかもしれないけど好きなアーティストやバンド",
          "好きなアウトドアアクティビティ",
          "解けないけど解きたいパズルやゲーム",
          "間違いから学んだ最も影響力のある教訓",
          "やめたい、または身につけたい習慣",
          "成果を祝う好きな方法",
          "なくてはならない技術製品",
          "披露できる珍しいスキルやパーティートリック",
          "これまで探検した中で最も興味深い場所",
          "子供の頃好きだった本",
          "長期連休中に始めた趣味",
          "成長する上で直面した最も大きな挑戦",
          "好きなポッドキャストとその理由",
          "誇りに思っている成果",
          "今までで最高の人生のアドバイス",
          "興味深いと思うランダムな事実",
          "目撃した最も心温まる出来事",
          "友達と遊ぶのに好きなボードゲームやカードゲーム",
          "絶対に破らない個人的なルール",
          "最後にした良い行い",
          "いつも気分を良くしてくれる映画",
          "平和を求めるときに逃げ込む好きな場所",
          "もっと知りたいと思う主題",
          "今まで試した中で最も珍しい食べ物",
          "家族と過ごす好きな方法",
        ]
    };
    let currentLanguage = 'en'; // 初期言語設定

    const languageToggle = document.getElementById('languageToggle');
    const generateButton = document.getElementById('generateButton');
    const promptDisplay = document.getElementById('promptDisplay');


        languageSelect.addEventListener('change', () => {
            // 選択されたオプションの値に基づいて言語を切り替える
            currentLanguage = languageSelect.value;
        });

        generateButton.addEventListener('click', () => {
            let intervalTime = 50;
            const maxIntervalTime = 300;
            const intervalIncrease = 25;
            const selectedPrompts = prompts[currentLanguage];

            const changePrompt = () => {
                promptDisplay.textContent = selectedPrompts[Math.floor(Math.random() * selectedPrompts.length)];
                if (intervalTime < maxIntervalTime) {
                    intervalTime += intervalIncrease;
                    setTimeout(changePrompt, intervalTime);
                }
            };

            setTimeout(changePrompt, intervalTime);
        });
    });
